/**
 * generate-pptx.ts
 *
 * Generates a styled .pptx from slides.md.
 *
 * Architecture: companion source/render pairs (per CLAUDE.md whiteboard
 * stylizer design). For every slide whose first speaker-note line is
 * `whiteboard=1`, the generator emits two physical slides:
 *
 *   - SOURCE slide  (filmstrip pos N, slide.hidden = true)
 *       Native, individually-editable primitives:
 *         - real addText for titles/body
 *         - real addTable for tables
 *         - real addChart (BAR / LINE / PIE) for chart showcases
 *         - real addShape compositions (rect / roundRect / line / ellipse +
 *           arrow endings) for flow / pillars / hub-spoke / roadmap
 *         - real addShape('line') for title underlines and section dividers
 *       Hidden in presentation mode but still visible in the filmstrip,
 *       so a human (or future restyle skill) can edit the source of truth.
 *
 *   - RENDER slide  (filmstrip pos N+1, visible)
 *       Same text, but tables / charts / diagrams / underlines are placed
 *       as rough.js PNG overlays at the same bounds. This is what the
 *       audience sees during a presentation.
 *
 * Both members of a pair carry a stable `pairId` in their speaker notes,
 * appended after any human notes via the sentinel
 *
 *     |This is autogenerated, please don't touch={...json...}
 *
 * so future tooling (e.g. a `/restylize` skill) can find the partner of
 * any slide and re-render the rough.js PNG overlays from the source's
 * current state.
 *
 * Slides without `whiteboard=1` get a single plain slide on the default
 * theme — no whiteboard background, no rough overlays.
 *
 * Usage: npx tsx generate-pptx.ts <slides.md> <output.pptx>
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import pptxgenModule from "pptxgenjs";
const pptxgen: any = (pptxgenModule as any).default || pptxgenModule;

const ICON_DIR = resolve("/workspaces/sashaslides/presentations/1/icons");
const ASSET_DIR = resolve("/workspaces/sashaslides/presentations/1/assets");
const GRAPHS_JSON = resolve("/workspaces/sashaslides/presentations/1/graphs.json");

// Showcase slides inserted at the beginning. Each is inherently whiteboard,
// so it always becomes a source/render pair regardless of slides.md markers.
const SHOWCASE_SLIDES: Array<{ name: string; title: string }> = [
  { name: "showcase_intro",     title: "The Whiteboard Graph Library" },
  { name: "showcase_bar",       title: "Bar Chart" },
  { name: "showcase_line",      title: "Line Chart" },
  { name: "showcase_pie",       title: "Pie Chart" },
  { name: "showcase_flow",      title: "Flow Diagram" },
  { name: "showcase_pillars",   title: "Pillars" },
  { name: "showcase_hubspoke",  title: "Hub & Spoke" },
  { name: "showcase_roadmap",   title: "Roadmap" },
];

// ── Icon mapping (decorative — placed identically on source and render) ───
const ICON_X = 10.9;
const ICON_Y = 0.75;
const ICON_SIZE = 1.5;
const CENTER_ICON_X = 13.33 / 2 - 0.5;
const CENTER_ICON_Y = 1.6;
const CENTER_ICON_SIZE = 1.0;

const SLIDE_ICONS: Record<number, { name: string; x?: number; y?: number; w?: number; h?: number }> = {
  0:  { name: "lightbulb",        x: CENTER_ICON_X, y: CENTER_ICON_Y, w: CENTER_ICON_SIZE, h: CENTER_ICON_SIZE },
  1:  { name: "arrow_right",      x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  3:  { name: "warning",          x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  4:  { name: "magnifying_glass", x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  5:  { name: "line_chart",       x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  7:  { name: "clock",            x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  8:  { name: "brain_chip",       x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  9:  { name: "bar_chart",        x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  10: { name: "money",            x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  12: { name: "soccer_ball",      x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  13: { name: "rocket",           x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  14: { name: "target",           x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  15: { name: "arrow_right",      x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  16: { name: "calendar",         x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  17: { name: "shield",           x: ICON_X,        y: ICON_Y,        w: ICON_SIZE,        h: ICON_SIZE },
  18: { name: "target",           x: CENTER_ICON_X, y: CENTER_ICON_Y, w: CENTER_ICON_SIZE, h: CENTER_ICON_SIZE },
};

// ── Slide parsing ──────────────────────────────────────────────────────────

type SlideData = {
  title: string;
  subtitle: string;
  bodyLines: string[];
  table: { headers: string[]; rows: string[][] } | null;
  notes: string;
  isSectionHeader: boolean;
  isTitleSlide: boolean;
  isClosing: boolean;
  whiteboard: boolean; // first `>` line was `whiteboard=1`
};

function parseSlides(md: string): SlideData[] {
  const blocks = md.split(/\n---\n/);
  const slides: SlideData[] = [];

  for (const block of blocks) {
    const lines = block.trim().split("\n").filter((l) => l.trim() !== "");
    if (lines.length === 0) continue;

    let title = "";
    let subtitle = "";
    const bodyLines: string[] = [];
    const notes: string[] = [];
    let isSectionHeader = false;
    let table: SlideData["table"] = null;
    let inTable = false;

    for (let li = 0; li < lines.length; li++) {
      const line = lines[li];

      if (line.startsWith(">")) {
        notes.push(line.replace(/^>\s*/, ""));
        continue;
      }

      if (line.includes("|") && !line.startsWith("#")) {
        const cells = line.split("|").map((c) => c.trim()).filter(Boolean);
        if (/^[\s|:-]+$/.test(line)) continue;
        if (!inTable) {
          const next = lines[li + 1];
          if (next && /^[\s|:-]+$/.test(next)) {
            table = { headers: cells, rows: [] };
            inTable = true;
            continue;
          }
        }
        if (inTable && table) {
          table = { ...table, rows: [...table.rows, cells] };
          continue;
        }
      } else {
        inTable = false;
      }

      if (/^#{1,2}\s/.test(line)) {
        const text = line.replace(/^#+\s+/, "").replace(/\*\*/g, "");
        if (text.startsWith("PART ")) {
          isSectionHeader = true;
          continue;
        }
        if (!title) title = text;
        else if (!subtitle) subtitle = text;
        continue;
      }

      bodyLines.push(line);
    }

    // Opt-in marker MUST be the first `>` line on the slide. Strip it
    // before computing subtitle/notes so it never leaks into displayed text.
    let whiteboard = false;
    if (notes[0] === "whiteboard=1") {
      whiteboard = true;
      notes.shift();
    }

    const isTitleSlide =
      lines[0]?.startsWith("# ") && bodyLines.length === 0 && !isSectionHeader && !table;
    const isClosing = title.toLowerCase().includes("thank you");

    if (notes.length > 0 && !subtitle) subtitle = notes[0];
    if (isTitleSlide && notes.length > 0) subtitle = notes.join(" | ");

    slides.push({
      title,
      subtitle,
      bodyLines,
      table,
      notes: notes.join("\n"),
      isSectionHeader,
      isTitleSlide,
      isClosing,
      whiteboard,
    });
  }

  return slides;
}

function cleanText(s: string): string {
  return s.replace(/\*\*/g, "");
}

function formatBodyText(line: string): { text: string; bold: boolean; bullet: boolean } {
  let text = line;
  let bullet = false;
  let bold = false;

  if (text.startsWith("- ") || text.startsWith("• ")) {
    text = text.slice(2);
    bullet = true;
  }
  const numMatch = text.match(/^(\d+)\.\s+(.*)/);
  if (numMatch) {
    text = numMatch[2];
    bullet = true;
  }
  if (line.match(/^\*\*[^*]+\*\*$/) || line.match(/^\*\*[^*]+:\*\*$/)) {
    bold = true;
  }
  text = cleanText(text);
  return { text, bold, bullet };
}

// ── Pair-id + sentinel notes ──────────────────────────────────────────────

const SENTINEL_PREFIX = "|This is autogenerated, please don't touch=";

/** Deterministic id derived from a seed string so re-running the generator
 *  yields the same pairId for the same logical slide. */
function pairIdFor(seed: string): string {
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  }
  return `pair_${h.toString(16).padStart(8, "0")}`;
}

function buildNotes(realNotes: string, payload: object): string {
  const json = JSON.stringify(payload);
  const sep = realNotes && !realNotes.endsWith("\n") ? "\n" : "";
  return `${realNotes}${sep}${SENTINEL_PREFIX}${json}`;
}

// ── Layout constants ──────────────────────────────────────────────────────

const TITLE_BLUE = "1A5276";
const TITLE_RED = "C0392B";
const BODY_DARK = "2C3E50";
const SUBTITLE_GRAY = "555555";

const TITLE_FONT = "Caveat";
const BODY_FONT = "Patrick Hand";

const SAFE_X = 0.9;
const SAFE_Y = 0.7;
const SAFE_W = 13.33 - 2 * SAFE_X;
const SAFE_H = 7.5 - SAFE_Y - 1.2;
const SAFE_BOTTOM = SAFE_Y + SAFE_H;

// ── Render order entry ────────────────────────────────────────────────────

type Entry =
  | { kind: "original"; data: SlideData; originalIndex: number }
  | { kind: "showcase"; name: string; title: string };

// Loaded once, used by showcase source builders.
let GRAPH_CFGS: Record<string, any> = {};

// ── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const slidesPath = process.argv[2] ?? "presentations/1/slides.md";
  const outputPath = process.argv[3] ?? "presentations/1/RobPresentation.pptx";

  const markdown = readFileSync(slidesPath, "utf-8");
  const slides = parseSlides(markdown);
  GRAPH_CFGS = JSON.parse(readFileSync(GRAPHS_JSON, "utf-8"));
  console.log(
    `Parsed ${slides.length} slides ` +
      `(${slides.filter((s) => s.whiteboard).length} marked whiteboard=1)`
  );

  const pres = new pptxgen();
  pres.layout = "LAYOUT_WIDE";
  pres.title = "Gemini Search Q2 Update for Rob";
  pres.author = "Search Triggering & Optimization Team";

  const WHITEBOARD_BG = resolve(
    "/workspaces/sashaslides/presentation-templates/whiteboard/whiteboard_background.png"
  );

  pres.defineSlideMaster({
    title: "WHITEBOARD",
    background: { color: "e8e8e8" },
    objects: [{ image: { path: WHITEBOARD_BG, x: 0, y: 0, w: 13.33, h: 7.5 } }],
  });

  pres.defineSlideMaster({
    title: "PLAIN",
    background: { color: "FFFFFF" },
  });

  // Build the render order: title slide (if any) + showcases + content slides.
  const hasTitleSlide = slides.length > 0 && slides[0].isTitleSlide;
  const titleSlideData = hasTitleSlide ? slides[0] : null;
  const contentSlidesData = hasTitleSlide ? slides.slice(1) : slides;

  const renderOrder: Entry[] = [];
  if (titleSlideData) {
    renderOrder.push({ kind: "original", data: titleSlideData, originalIndex: 0 });
  }
  for (const sc of SHOWCASE_SLIDES) {
    renderOrder.push({ kind: "showcase", name: sc.name, title: sc.title });
  }
  const startIdx = hasTitleSlide ? 1 : 0;
  for (let j = 0; j < contentSlidesData.length; j++) {
    renderOrder.push({ kind: "original", data: contentSlidesData[j], originalIndex: startIdx + j });
  }

  // Counters for cycling per-slide unique underline / divider variants
  let contentSlideCounter = 0;
  let sectionCounter = 0;

  for (let orderIdx = 0; orderIdx < renderOrder.length; orderIdx++) {
    const entry = renderOrder[orderIdx];

    const isWhiteboard =
      entry.kind === "showcase" || (entry.kind === "original" && entry.data.whiteboard);

    if (!isWhiteboard) {
      addPlainSlide(pres, entry as Extract<Entry, { kind: "original" }>);
      continue;
    }

    const seed =
      entry.kind === "showcase"
        ? `showcase:${entry.name}`
        : `slide:${entry.originalIndex}:${entry.data.title}`;
    const pairId = pairIdFor(seed);

    addSourceSlide(pres, entry, pairId);

    // Pick which unique underline/divider variant this render slide gets.
    const underlineVariant = contentSlideCounter % 6;
    const sectionVariant = sectionCounter;
    const isContentWithUnderline =
      entry.kind === "original" &&
      !entry.data.isSectionHeader &&
      !entry.data.isTitleSlide &&
      !entry.data.isClosing;
    if (isContentWithUnderline) contentSlideCounter++;
    if (entry.kind === "original" && entry.data.isSectionHeader) sectionCounter++;

    addRenderSlide(pres, entry, pairId, underlineVariant, sectionVariant);
  }

  await pres.writeFile({ fileName: outputPath });
  console.log(`Wrote ${outputPath}`);
}

// ── Source slide builders (native primitives) ─────────────────────────────

function addSourceSlide(pres: any, entry: Entry, pairId: string): void {
  const slide = pres.addSlide({ masterName: "WHITEBOARD" });
  slide.hidden = true;

  const realNotes = entry.kind === "original" ? entry.data.notes : "";
  slide.addNotes(buildNotes(realNotes, { role: "source", pairId, kind: entry.kind }));

  if (entry.kind === "showcase") {
    addShowcaseSourceContent(pres, slide, entry);
  } else {
    addOriginalSourceContent(slide, entry.data, entry.originalIndex);
  }
}

function addOriginalSourceContent(slide: any, s: SlideData, i: number): void {
  const iconCfg = SLIDE_ICONS[i];
  if (iconCfg) {
    slide.addImage({
      path: `${ICON_DIR}/${iconCfg.name}.png`,
      x: iconCfg.x ?? 11.3,
      y: iconCfg.y ?? 0.3,
      w: iconCfg.w ?? 1.6,
      h: iconCfg.h ?? 1.6,
    });
  }

  if (s.isTitleSlide || s.isClosing) {
    slide.addText(s.title, {
      x: SAFE_X, y: SAFE_Y + SAFE_H * 0.3, w: SAFE_W, h: 1.5,
      fontFace: TITLE_FONT, fontSize: 56, bold: true, color: TITLE_RED,
      align: "center", valign: "middle", fit: "shrink",
    });
    if (s.subtitle) {
      slide.addText(cleanText(s.subtitle), {
        x: SAFE_X, y: SAFE_Y + SAFE_H * 0.65, w: SAFE_W, h: 0.8,
        fontFace: BODY_FONT, fontSize: 26, color: SUBTITLE_GRAY, align: "center",
      });
    }
    return;
  }

  if (s.isSectionHeader) {
    const midY = SAFE_Y + SAFE_H / 2;
    // Native straight-line dividers — editable, will be replaced by rough
    // PNG overlays on the render slide.
    slide.addShape("line", {
      x: SAFE_X + SAFE_W * 0.25, y: midY - 0.5, w: SAFE_W * 0.5, h: 0,
      line: { color: TITLE_BLUE, width: 4 },
    });
    slide.addText(cleanText(s.title), {
      x: SAFE_X, y: midY - 0.65, w: SAFE_W, h: 1.3,
      fontFace: TITLE_FONT, fontSize: 50, bold: true, color: TITLE_BLUE,
      align: "center", valign: "middle", fit: "shrink",
    });
    slide.addShape("line", {
      x: SAFE_X + SAFE_W * 0.25, y: midY + 0.85, w: SAFE_W * 0.5, h: 0,
      line: { color: TITLE_RED, width: 4 },
    });
    return;
  }

  // Regular content slide
  const hasIconTopRight = !!(iconCfg && iconCfg.x && iconCfg.x > 8);
  const titleW = hasIconTopRight ? SAFE_W - 1.8 : SAFE_W;

  slide.addText(cleanText(s.title), {
    x: SAFE_X, y: SAFE_Y, w: titleW, h: 0.75,
    fontFace: TITLE_FONT, fontSize: 34, bold: true, color: TITLE_BLUE,
    align: "left", fit: "shrink",
  });

  // Native title underline (editable straight blue line)
  slide.addShape("line", {
    x: SAFE_X, y: SAFE_Y + 0.78, w: titleW, h: 0,
    line: { color: TITLE_BLUE, width: 3 },
  });

  const hasTable = s.table !== null;
  const hasBody = s.bodyLines.length > 0;

  if (hasBody) {
    const bodyTextRuns = s.bodyLines.map((line) => {
      const f = formatBodyText(line);
      return {
        text: (f.bullet ? "• " : "") + f.text,
        options: {
          fontFace: BODY_FONT,
          fontSize: f.bold ? 20 : 16,
          color: f.bold ? TITLE_RED : BODY_DARK,
          bold: f.bold,
          breakLine: true,
        },
      };
    });
    const contentY = SAFE_Y + 1.0;
    const contentH = SAFE_BOTTOM - contentY;
    const bodyW = hasTable ? SAFE_W * 0.48 : SAFE_W;
    slide.addText(bodyTextRuns as any, {
      x: SAFE_X, y: contentY, w: bodyW, h: contentH, valign: "top",
    });
  }

  if (hasTable && s.table) {
    // NATIVE editable table — this is the source of truth for cell values.
    const contentY = SAFE_Y + 1.0;
    const tableW = hasBody ? SAFE_W * 0.48 : SAFE_W;
    const tableX = hasBody ? SAFE_X + SAFE_W * 0.5 + 0.2 : SAFE_X;

    const headerRow = s.table.headers.map((h) => ({
      text: cleanText(h),
      options: {
        bold: true,
        color: TITLE_BLUE,
        fill: { color: "D6EAF8" },
        fontFace: TITLE_FONT,
        fontSize: 18,
        align: "center" as const,
      },
    }));
    const dataRows = s.table.rows.map((row) =>
      row.map((cell) => ({
        text: cleanText(cell),
        options: {
          color: BODY_DARK,
          fontFace: BODY_FONT,
          fontSize: 14,
          align: "center" as const,
        },
      }))
    );
    slide.addTable([headerRow, ...dataRows] as any, {
      x: tableX, y: contentY, w: tableW,
      border: { type: "solid", pt: 1, color: BODY_DARK },
      autoPage: false,
    });
  }
}

function addShowcaseSourceContent(
  pres: any,
  slide: any,
  entry: Extract<Entry, { kind: "showcase" }>
): void {
  const cfg = GRAPH_CFGS[entry.name] || {};

  slide.addText(cfg.title || entry.title, {
    x: SAFE_X, y: SAFE_Y, w: SAFE_W, h: 0.9,
    fontFace: TITLE_FONT, fontSize: 44, bold: true, color: TITLE_BLUE,
    align: "left",
  });
  if (cfg.subtitle) {
    slide.addText(cfg.subtitle, {
      x: SAFE_X, y: SAFE_Y + 0.9, w: SAFE_W, h: 0.5,
      fontFace: BODY_FONT, fontSize: 22, color: SUBTITLE_GRAY, align: "left",
    });
  }

  const chartX = SAFE_X + 1.0;
  const chartY = SAFE_Y + 1.6;
  const chartW = SAFE_W - 2.0;
  const chartH = SAFE_BOTTOM - chartY - 0.2;

  switch (cfg.type) {
    case "barChart": {
      const labels = (cfg.data || []).map((d: any) => d.label);
      const values = (cfg.data || []).map((d: any) => d.value);
      slide.addChart(
        "bar",
        [{ name: cfg.opts?.title || "Series", labels, values }],
        {
          x: chartX, y: chartY, w: chartW, h: chartH,
          barDir: "col",
          showTitle: !!cfg.opts?.title,
          title: cfg.opts?.title || "",
          titleColor: TITLE_BLUE,
          chartColors: [TITLE_BLUE],
          catAxisLabelColor: BODY_DARK,
          valAxisLabelColor: BODY_DARK,
          showValue: true,
        }
      );
      break;
    }
    case "lineChart": {
      const labels = (cfg.data || []).map((d: any) => d.label);
      const values = (cfg.data || []).map((d: any) => d.value);
      slide.addChart(
        "line",
        [{ name: cfg.opts?.title || "Series", labels, values }],
        {
          x: chartX, y: chartY, w: chartW, h: chartH,
          showTitle: !!cfg.opts?.title,
          title: cfg.opts?.title || "",
          titleColor: TITLE_BLUE,
          chartColors: [TITLE_BLUE],
        }
      );
      break;
    }
    case "pieChart": {
      const labels = (cfg.data || []).map((d: any) => d.label);
      const values = (cfg.data || []).map((d: any) => d.value);
      slide.addChart(
        "pie",
        [{ name: cfg.opts?.title || "Series", labels, values }],
        {
          x: chartX, y: chartY, w: chartW, h: chartH,
          showTitle: !!cfg.opts?.title,
          title: cfg.opts?.title || "",
          titleColor: TITLE_BLUE,
          showLegend: true,
          legendPos: "r",
        }
      );
      break;
    }
    case "flowDiagram": {
      // graphs.json positions are in an 800x600 reference frame
      const REF_W = 800, REF_H = 600;
      const sx = (px: number) => chartX + (px / REF_W) * chartW;
      const sy = (px: number) => chartY + (px / REF_H) * chartH;
      const sw = (px: number) => (px / REF_W) * chartW;
      const sh = (px: number) => (px / REF_H) * chartH;

      for (const node of cfg.nodes || []) {
        slide.addShape("roundRect", {
          x: sx(node.x), y: sy(node.y), w: sw(node.w), h: sh(node.h),
          fill: { color: "D6EAF8" },
          line: { color: TITLE_BLUE, width: 2 },
        });
        slide.addText(node.label, {
          x: sx(node.x), y: sy(node.y), w: sw(node.w), h: sh(node.h),
          fontFace: BODY_FONT, fontSize: 16, color: TITLE_BLUE,
          align: "center", valign: "middle",
        });
      }
      const nodeMap: Record<string, any> = Object.fromEntries(
        (cfg.nodes || []).map((n: any) => [n.id, n])
      );
      for (const edge of cfg.edges || []) {
        const from = nodeMap[edge.from];
        const to = nodeMap[edge.to];
        if (!from || !to) continue;
        const x1 = sx(from.x + from.w);
        const y1 = sy(from.y + from.h / 2);
        const x2 = sx(to.x);
        const y2 = sy(to.y + to.h / 2);
        slide.addShape("line", {
          x: x1, y: y1, w: x2 - x1, h: y2 - y1,
          line: { color: BODY_DARK, width: 2, endArrowType: "triangle" },
        });
      }
      break;
    }
    case "pillars": {
      const labels: string[] = cfg.pillarLabels || [];
      const cellW = chartW / labels.length;
      const pillarW = cellW * 0.55;
      const topBarY = chartY + 0.5;
      const baseBarY = chartY + chartH - 0.5;
      const pillarTop = topBarY + 0.35;
      const pillarBottom = baseBarY - 0.05;
      const pillarH = pillarBottom - pillarTop;

      // Top bar
      slide.addShape("rect", {
        x: chartX, y: topBarY, w: chartW, h: 0.3,
        fill: { color: TITLE_BLUE }, line: { color: TITLE_BLUE, width: 1 },
      });
      // Base bar
      slide.addShape("rect", {
        x: chartX, y: baseBarY, w: chartW, h: 0.3,
        fill: { color: TITLE_BLUE }, line: { color: TITLE_BLUE, width: 1 },
      });

      for (let k = 0; k < labels.length; k++) {
        const cellX = chartX + k * cellW + (cellW - pillarW) / 2;
        slide.addShape("rect", {
          x: cellX, y: pillarTop, w: pillarW, h: pillarH,
          fill: { color: "D6EAF8" }, line: { color: TITLE_BLUE, width: 2 },
        });
        slide.addText(labels[k], {
          x: cellX, y: pillarTop, w: pillarW, h: pillarH,
          fontFace: BODY_FONT, fontSize: 18, color: TITLE_BLUE,
          align: "center", valign: "middle",
        });
      }

      if (cfg.opts?.topLabel) {
        slide.addText(cfg.opts.topLabel, {
          x: chartX, y: topBarY - 0.6, w: chartW, h: 0.5,
          fontFace: TITLE_FONT, fontSize: 22, bold: true, color: TITLE_BLUE,
          align: "center",
        });
      }
      if (cfg.opts?.baseLabel) {
        slide.addText(cfg.opts.baseLabel, {
          x: chartX, y: baseBarY + 0.35, w: chartW, h: 0.5,
          fontFace: TITLE_FONT, fontSize: 22, bold: true, color: TITLE_BLUE,
          align: "center",
        });
      }
      break;
    }
    case "hubSpoke": {
      const cx = chartX + chartW / 2;
      const cy = chartY + chartH / 2;
      const hubW = 1.8, hubH = 1.0;
      slide.addShape("ellipse", {
        x: cx - hubW / 2, y: cy - hubH / 2, w: hubW, h: hubH,
        fill: { color: "D6EAF8" }, line: { color: TITLE_BLUE, width: 2 },
      });
      slide.addText(cfg.centerLabel || "", {
        x: cx - hubW / 2, y: cy - hubH / 2, w: hubW, h: hubH,
        fontFace: TITLE_FONT, fontSize: 22, bold: true, color: TITLE_BLUE,
        align: "center", valign: "middle",
      });
      const spokes: any[] = cfg.spokes || [];
      const r = Math.min(chartW, chartH) * 0.36;
      const sw = 1.4, sh = 0.6;
      for (let k = 0; k < spokes.length; k++) {
        const angle = (k / spokes.length) * Math.PI * 2 - Math.PI / 2;
        const ex = cx + Math.cos(angle) * r;
        const ey = cy + Math.sin(angle) * r;
        slide.addShape("line", {
          x: cx, y: cy, w: ex - cx, h: ey - cy,
          line: { color: BODY_DARK, width: 2 },
        });
        slide.addShape("ellipse", {
          x: ex - sw / 2, y: ey - sh / 2, w: sw, h: sh,
          fill: { color: "FFFFFF" }, line: { color: TITLE_BLUE, width: 2 },
        });
        slide.addText(spokes[k].label || "", {
          x: ex - sw / 2, y: ey - sh / 2, w: sw, h: sh,
          fontFace: BODY_FONT, fontSize: 14, color: TITLE_BLUE,
          align: "center", valign: "middle",
        });
      }
      break;
    }
    case "roadmap": {
      const stages: any[] = cfg.stages || [];
      const cellW = chartW / stages.length;
      const stageW = cellW * 0.78;
      const stageH = 1.1;
      const yMid = chartY + chartH / 2 - stageH / 2;
      for (let k = 0; k < stages.length; k++) {
        const x = chartX + k * cellW + (cellW - stageW) / 2;
        slide.addShape("roundRect", {
          x, y: yMid, w: stageW, h: stageH,
          fill: { color: "D6EAF8" }, line: { color: TITLE_BLUE, width: 2 },
        });
        slide.addText(stages[k].label || "", {
          x, y: yMid + 0.05, w: stageW, h: stageH * 0.55,
          fontFace: TITLE_FONT, fontSize: 22, bold: true, color: TITLE_BLUE,
          align: "center", valign: "middle",
        });
        if (stages[k].sublabel) {
          slide.addText(stages[k].sublabel, {
            x, y: yMid + stageH * 0.55, w: stageW, h: stageH * 0.4,
            fontFace: BODY_FONT, fontSize: 14, color: BODY_DARK,
            align: "center", valign: "middle",
          });
        }
        if (k < stages.length - 1) {
          const ax1 = x + stageW;
          const ax2 = chartX + (k + 1) * cellW + (cellW - stageW) / 2;
          const ay = yMid + stageH / 2;
          slide.addShape("line", {
            x: ax1, y: ay, w: ax2 - ax1, h: 0,
            line: { color: BODY_DARK, width: 3, endArrowType: "triangle" },
          });
        }
      }
      break;
    }
    default: {
      slide.addText("(diagram source — see graphs.json)", {
        x: chartX, y: chartY, w: chartW, h: chartH,
        fontFace: BODY_FONT, fontSize: 18, color: SUBTITLE_GRAY,
        align: "center", valign: "middle",
      });
    }
  }
}

// ── Render slide builders (rough.js PNG overlays) ─────────────────────────

function addRenderSlide(
  pres: any,
  entry: Entry,
  pairId: string,
  underlineVariant: number,
  sectionVariant: number
): void {
  const slide = pres.addSlide({ masterName: "WHITEBOARD" });
  const realNotes = entry.kind === "original" ? entry.data.notes : "";
  const overlays: any[] = [];

  if (entry.kind === "showcase") {
    addShowcaseRenderContent(slide, entry, overlays);
  } else {
    addOriginalRenderContent(
      slide, entry.data, entry.originalIndex,
      underlineVariant, sectionVariant, overlays
    );
  }

  slide.addNotes(
    buildNotes(realNotes, { role: "render", pairId, kind: entry.kind, overlays })
  );
}

function addShowcaseRenderContent(
  slide: any,
  entry: Extract<Entry, { kind: "showcase" }>,
  overlays: any[]
): void {
  const path = `${ASSET_DIR}/showcases/${entry.name}.png`;
  slide.addImage({
    path, x: SAFE_X, y: SAFE_Y, w: SAFE_W, h: SAFE_H,
    altText: `graph:${entry.name}`,
  } as any);
  overlays.push({ kind: "showcase", name: entry.name, x: SAFE_X, y: SAFE_Y, w: SAFE_W, h: SAFE_H });
}

function addOriginalRenderContent(
  slide: any,
  s: SlideData,
  i: number,
  underlineVariant: number,
  sectionVariant: number,
  overlays: any[]
): void {
  const iconCfg = SLIDE_ICONS[i];
  if (iconCfg) {
    slide.addImage({
      path: `${ICON_DIR}/${iconCfg.name}.png`,
      x: iconCfg.x ?? 11.3,
      y: iconCfg.y ?? 0.3,
      w: iconCfg.w ?? 1.6,
      h: iconCfg.h ?? 1.6,
    });
  }

  if (s.isTitleSlide || s.isClosing) {
    slide.addText(s.title, {
      x: SAFE_X, y: SAFE_Y + SAFE_H * 0.3, w: SAFE_W, h: 1.5,
      fontFace: TITLE_FONT, fontSize: 56, bold: true, color: TITLE_RED,
      align: "center", valign: "middle", fit: "shrink",
    });
    slide.addText("→", {
      x: SAFE_X + SAFE_W / 2 - 0.5, y: SAFE_Y + SAFE_H * 0.55, w: 1, h: 0.5,
      fontFace: TITLE_FONT, fontSize: 32, color: TITLE_RED, align: "center",
    });
    if (s.subtitle) {
      slide.addText(cleanText(s.subtitle), {
        x: SAFE_X, y: SAFE_Y + SAFE_H * 0.65, w: SAFE_W, h: 0.8,
        fontFace: BODY_FONT, fontSize: 26, color: SUBTITLE_GRAY, align: "center",
      });
    }
    return;
  }

  if (s.isSectionHeader) {
    const midY = SAFE_Y + SAFE_H / 2;
    const divW = SAFE_W * 0.5;
    const divH = divW * (48 / 2400);
    const blueName = `underline_${sectionVariant % 6}`;
    const redName = `underline_red_${sectionVariant % 3}`;
    slide.addImage({
      path: `${ASSET_DIR}/${blueName}.png`,
      x: SAFE_X + SAFE_W * 0.25, y: midY - 0.55, w: divW, h: divH,
    });
    overlays.push({
      kind: "section-divider", color: "blue", variant: blueName,
      x: SAFE_X + SAFE_W * 0.25, y: midY - 0.55, w: divW, h: divH,
    });

    slide.addText(cleanText(s.title), {
      x: SAFE_X, y: midY - 0.65, w: SAFE_W, h: 1.3,
      fontFace: TITLE_FONT, fontSize: 50, bold: true, color: TITLE_BLUE,
      align: "center", valign: "middle", fit: "shrink",
    });

    slide.addImage({
      path: `${ASSET_DIR}/${redName}.png`,
      x: SAFE_X + SAFE_W * 0.25, y: midY + 0.78, w: divW, h: divH,
    });
    overlays.push({
      kind: "section-divider", color: "red", variant: redName,
      x: SAFE_X + SAFE_W * 0.25, y: midY + 0.78, w: divW, h: divH,
    });
    return;
  }

  // Regular content slide
  const hasIconTopRight = !!(iconCfg && iconCfg.x && iconCfg.x > 8);
  const titleW = hasIconTopRight ? SAFE_W - 1.8 : SAFE_W;

  slide.addText(cleanText(s.title), {
    x: SAFE_X, y: SAFE_Y, w: titleW, h: 0.75,
    fontFace: TITLE_FONT, fontSize: 34, bold: true, color: TITLE_BLUE,
    align: "left", fit: "shrink",
  });

  const ulName = `underline_${underlineVariant % 6}`;
  const ulH = titleW * (48 / 2400);
  slide.addImage({
    path: `${ASSET_DIR}/${ulName}.png`,
    x: SAFE_X, y: SAFE_Y + 0.78, w: titleW, h: ulH,
  });
  overlays.push({
    kind: "title-underline", variant: ulName,
    x: SAFE_X, y: SAFE_Y + 0.78, w: titleW, h: ulH,
  });

  const hasTable = s.table !== null;
  const hasBody = s.bodyLines.length > 0;

  if (hasBody) {
    const bodyTextRuns = s.bodyLines.map((line) => {
      const f = formatBodyText(line);
      return {
        text: (f.bullet ? "• " : "") + f.text,
        options: {
          fontFace: BODY_FONT,
          fontSize: f.bold ? 20 : 16,
          color: f.bold ? TITLE_RED : BODY_DARK,
          bold: f.bold,
          breakLine: true,
        },
      };
    });
    const contentY = SAFE_Y + 1.0;
    const contentH = SAFE_BOTTOM - contentY;
    const bodyW = hasTable ? SAFE_W * 0.48 : SAFE_W;
    slide.addText(bodyTextRuns as any, {
      x: SAFE_X, y: contentY, w: bodyW, h: contentH, valign: "top",
    });
  }

  if (hasTable && s.table) {
    const contentY = SAFE_Y + 1.0;
    const tableImgPath = `${ASSET_DIR}/tables/table_${String(i).padStart(2, "0")}.png`;
    const hasBodyContent = s.bodyLines.length > 0;
    const tableW = hasBodyContent ? SAFE_W * 0.48 : SAFE_W;
    const pxW = hasBodyContent ? 620 : 1200;
    const pxH = 70 + s.table.rows.length * 55;
    const tableH = (pxH / pxW) * tableW;
    const tableX = hasBodyContent ? SAFE_X + SAFE_W * 0.5 + 0.2 : SAFE_X;
    slide.addImage({ path: tableImgPath, x: tableX, y: contentY, w: tableW, h: tableH });
    overlays.push({ kind: "table", x: tableX, y: contentY, w: tableW, h: tableH });
  }
}

// ── Plain (unmarked) slides ──────────────────────────────────────────────

function addPlainSlide(pres: any, entry: Extract<Entry, { kind: "original" }>): void {
  const s = entry.data;
  const slide = pres.addSlide({ masterName: "PLAIN" });
  if (s.notes) slide.addNotes(s.notes);

  if (s.isTitleSlide || s.isClosing) {
    slide.addText(s.title, {
      x: 0.5, y: 2.5, w: 12.33, h: 1.5,
      fontSize: 44, bold: true, color: "222222", align: "center",
    });
    if (s.subtitle) {
      slide.addText(cleanText(s.subtitle), {
        x: 0.5, y: 4.0, w: 12.33, h: 0.8,
        fontSize: 22, color: "555555", align: "center",
      });
    }
    return;
  }

  if (s.isSectionHeader) {
    slide.addText(cleanText(s.title), {
      x: 0.5, y: 3.0, w: 12.33, h: 1.5,
      fontSize: 40, bold: true, color: "222222", align: "center",
    });
    return;
  }

  slide.addText(cleanText(s.title), {
    x: 0.5, y: 0.4, w: 12.33, h: 0.9,
    fontSize: 28, bold: true, color: "222222",
  });

  const bodyRuns = s.bodyLines.map((line) => {
    const f = formatBodyText(line);
    return {
      text: (f.bullet ? "• " : "") + f.text,
      options: { fontSize: f.bold ? 18 : 14, bold: f.bold, color: "333333", breakLine: true },
    };
  });
  slide.addText(bodyRuns as any, {
    x: 0.5, y: 1.5, w: 12.33, h: 5.0, valign: "top",
  });

  if (s.table) {
    const headerRow = s.table.headers.map((h) => ({
      text: cleanText(h),
      options: { bold: true, fill: { color: "EEEEEE" }, fontSize: 14 },
    }));
    const dataRows = s.table.rows.map((row) =>
      row.map((cell) => ({ text: cleanText(cell), options: { fontSize: 12 } }))
    );
    slide.addTable([headerRow, ...dataRows] as any, {
      x: 0.5, y: 5.5, w: 12.33,
      border: { type: "solid", pt: 1, color: "999999" },
    });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
