/**
 * clusters.ts — AUTO-GENERATED by generate-clusters.ts from the reconciled,
 * checked bad set. ONE Cluster per bad slide (no grouping heuristic → no
 * wrong-grouping regressions). Re-generate with:
 *   npx tsx renderer/structured-prompts/bug_solving/reconcile-and-check.ts --emit-clusters
 * Review the diff before launching a solve; a human owns the final clusters.ts.
 */
import type { Cluster } from "./workspace-setup.js";

const C_SLIDE_03: Cluster = {
  task_id: "slide-03-everything-moved-bit",
  slide_ids: ["slide_03"],
  retry_budget: 5,
  cluster_description: "slide_03 — Everything is moved up a bit everywhere, entire list, small 0.3pp down, bars on graphs.\n\nApproach: analyze the TARGET (original) vs the ATTEMPT (current render) + the annotation, find the ROOT CAUSE in renderer/html2slides/extract-dom.ts and/or convert-pptx*.ts, apply the MINIMAL fix, and DO NOT regress the other slides (render a couple of neighbours to confirm).",
};

const C_SLIDE_11: Cluster = {
  task_id: "slide-11-list-output-possible",
  slide_ids: ["slide_11"],
  retry_budget: 5,
  cluster_description: "slide_11 — Not a list in output, is it possible to color bullets in a list element?\n\nApproach: analyze the TARGET (original) vs the ATTEMPT (current render) + the annotation, find the ROOT CAUSE in renderer/html2slides/extract-dom.ts and/or convert-pptx*.ts, apply the MINIMAL fix, and DO NOT regress the other slides (render a couple of neighbours to confirm).",
};

const C_SLIDE_13: Cluster = {
  task_id: "slide-13-many-rendered-regions",
  slide_ids: ["slide_13"],
  retry_budget: 5,
  cluster_description: "slide_13 — Why are there so many rendered regions on the right, this looks like it should be possible to support trapezoid shape and more generic shapes with gradient.\n\nApproach: analyze the TARGET (original) vs the ATTEMPT (current render) + the annotation, find the ROOT CAUSE in renderer/html2slides/extract-dom.ts and/or convert-pptx*.ts, apply the MINIMAL fix, and DO NOT regress the other slides (render a couple of neighbours to confirm).",
};

const C_SLIDE_14: Cluster = {
  task_id: "slide-14-top-border-style",
  slide_ids: ["slide_14"],
  retry_budget: 5,
  cluster_description: "slide_14 — The top border style is transferred wrong, like rounded border vs straight top line which is clipped by the mask of the element (there is clipping code which works recursively when it tries to then overlap clipping elements and reuse some existing ones.\nIn this case there should be an element which can present this cut.\n\nApproach: analyze the TARGET (original) vs the ATTEMPT (current render) + the annotation, find the ROOT CAUSE in renderer/html2slides/extract-dom.ts and/or convert-pptx*.ts, apply the MINIMAL fix, and DO NOT regress the other slides (render a couple of neighbours to confirm).",
};

export const CLUSTERS: Cluster[] = [C_SLIDE_03, C_SLIDE_11, C_SLIDE_13, C_SLIDE_14];
