/**
 * Scaffolding that boots the engine, sets up the demo workspaces, and runs
 * the structured prompt defined in ./main.ts. In production this file is
 * typically generated by a model into a temp directory — it's the "how do I
 * actually invoke the library" part that rarely needs to change. We keep it
 * in-tree for the demo.
 */

import { ClaudeEngine, Session } from "../src/index.js";
import { buildExampleWorkspaces } from "./workspace-setup.js";
import { main } from "./main.js";

async function runExample() {
  const tasks = buildExampleWorkspaces();
  const engine = new ClaudeEngine({ port: 4711, persist: true });
  const session = new Session({ sessionId: "sp-example-root" });
  const results = await engine.execute(session, (s) => main({ session: s, tasks }));
  console.error("\n=== RESULTS ===");
  console.error(JSON.stringify(results, null, 2));
  console.error(`\nMonitor still live at ${engine.monitorUrl}`);
  console.error("Press Ctrl-C to shut it down.");
}

runExample().catch((e) => {
  console.error("example crashed:", e);
  process.exit(1);
});
