#!/usr/bin/env npx tsx
/**
 * build-addon.ts — Bundles the Google Slides add-on (sidebar + bound Apps
 * Script) from the shared browser conversion core.
 *
 * It mirrors build.ts (same esbuild config / vendor inlining) but targets the
 * add-on instead of a standalone page. Output is a ready-to-push Apps Script
 * project under the repo-root dist/ (gitignored), mirroring the source path:
 *
 *   dist/renderer/html2slides/addon/
 *     appsscript.json   — manifest: V8, OAuth scopes, Advanced Drive Service
 *     Code.gs           — server: onOpen menu + showSidebar + insertPptxAfterCurrent
 *     Sidebar.html      — the html2slides UI with the whole client bundle inlined
 *
 * Push it with clasp (`cd dist/renderer/html2slides/addon && clasp push`) or
 * paste the three files into Extensions → Apps Script. See addon/README.md.
 */
import { build, transformSync } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../../..");
const OUT = join(ROOT, "dist", "renderer", "html2slides", "addon");

function readText(p: string): string { return readFileSync(p, "utf-8"); }

// ---------------------------------------------------------------------------
// Apps Script server (Code.gs) — plain V8 JavaScript, served as a .gs file.
// ---------------------------------------------------------------------------
const CODE_GS = `/**
 * html2slides — Google Slides add-on server.
 *
 * The sidebar (Sidebar.html) builds the .pptx entirely client-side and sends
 * the bytes here as base64. We convert them to a temporary Google Slides file
 * via the Advanced Drive Service (same importer as File > Import slides), then
 * copy every slide into the active presentation right AFTER the current slide,
 * and finally delete the temp file.
 *
 * AUTOGENERATED by build-addon.ts — edit the source, not dist/Code.gs.
 */

function onOpen(e) {
  SlidesApp.getUi()
    .createAddonMenu()
    .addItem('Open html2slides', 'showSidebar')
    .addToUi();
}

function onInstall(e) {
  onOpen(e);
}

function showSidebar() {
  var html = HtmlService.createHtmlOutputFromFile('Sidebar').setTitle('html2slides');
  SlidesApp.getUi().showSidebar(html);
}

/**
 * Returns the consent URL + current status so the sidebar can offer a
 * "Re-authorize" button. Apps Script does NOT re-prompt automatically once the
 * scopes are granted (the v2->v3 Drive switch added no new scope), so a manual
 * re-grant is the only way to refresh a stale/partial Drive authorization that
 * causes PERMISSION_DENIED.
 * @return {{status:string, url:string}}
 */
function getAuthInfo() {
  var info = ScriptApp.getAuthorizationInfo(ScriptApp.AuthMode.FULL);
  return { status: String(info.getAuthorizationStatus()), url: info.getAuthorizationUrl() };
}

/** Touch Drive with the user's auth so a missing/!granted drive scope throws
 * the standard authorization prompt instead of a generic storage error. Used
 * by the sidebar's "Test permissions" button. */
function testDriveAccess() {
  var about = Drive.About.get({ fields: 'user' }); // requires the drive scope
  return { ok: true, user: about && about.user ? about.user.emailAddress : '(unknown)' };
}

/**
 * @param {string} base64  the .pptx bytes, base64-encoded
 * @param {string} title   display name for the temp converted file
 * @return {{inserted:number, at:number, title:string}}
 */
function insertPptxAfterCurrent(base64, title) {
  title = title || 'html2slides import';
  var blob = Utilities.newBlob(
    Utilities.base64Decode(base64),
    MimeType.MICROSOFT_POWERPOINT,
    title + '.pptx'
  );

  var tempId = null;
  try {
    // 1. Upload + convert pptx -> a temporary Google Slides file. Drive v3:
    //    uploading a blob whose target resource mimeType is a Google type
    //    converts it (the modern equivalent of the v2 convert:true flag, which
    //    Google has sunset — its failure surfaces as PERMISSION_DENIED /
    //    "server error occurred while reading from storage").
    var converted = Drive.Files.create(
      { name: title, mimeType: MimeType.GOOGLE_SLIDES },
      blob
    );
    tempId = converted.id;

    // A just-converted file can briefly 404 / PERMISSION_DENIED before its
    // storage settles; retry openById a few times with a short backoff.
    var src = null;
    for (var attempt = 0; attempt < 5; attempt++) {
      try { src = SlidesApp.openById(tempId); break; }
      catch (openErr) {
        if (attempt === 4) throw openErr;
        Utilities.sleep(600);
      }
    }
    var srcSlides = src.getSlides();
    if (!srcSlides.length) throw new Error('converted deck had no slides');

    var pres = SlidesApp.getActivePresentation();
    var slides = pres.getSlides();

    // 2. Where is the current slide? Insert right after it; fall back to the end.
    var insertAt = slides.length;
    var sel = pres.getSelection();
    var cur = sel ? sel.getCurrentPage() : null;
    if (cur) {
      var curId = cur.getObjectId();
      for (var i = 0; i < slides.length; i++) {
        if (slides[i].getObjectId() === curId) { insertAt = i + 1; break; }
      }
    }

    // 3. Copy each source slide (with formatting) into the active deck.
    var firstAt = insertAt;
    for (var j = 0; j < srcSlides.length; j++) {
      pres.insertSlide(insertAt++, srcSlides[j]);
    }

    return { inserted: srcSlides.length, at: firstAt + 1, title: title };
  } finally {
    // 4. Best-effort cleanup of the temp file.
    if (tempId) {
      try { Drive.Files.remove(tempId); } catch (err) { /* leave it in Trash */ }
    }
  }
}
`;

// ---------------------------------------------------------------------------
// Apps Script manifest. Full presentations + drive scopes are needed because
// we openById() a *separate* converted file and write into the active deck;
// the Advanced Drive Service (v3) provides the pptx->Slides conversion (upload
// a blob with a Google target mimeType). v2's convert flag has been sunset.
// ---------------------------------------------------------------------------
const APPSSCRIPT_JSON = JSON.stringify({
  timeZone: "Etc/UTC",
  exceptionLogging: "STACKDRIVER",
  runtimeVersion: "V8",
  oauthScopes: [
    "https://www.googleapis.com/auth/presentations",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/script.container.ui",
  ],
  dependencies: {
    enabledAdvancedServices: [
      { userSymbol: "Drive", serviceId: "drive", version: "v3" },
    ],
  },
}, null, 2);

async function main() {
  // 1. Compile extract-dom.ts -> JS string (same as build.ts).
  const extractTs = readText(join(HERE, "..", "extract-dom.ts"));
  const extractJs = transformSync(extractTs, { loader: "ts", target: "es2020" }).code;
  console.log(`extract-dom.ts → ${extractJs.length.toLocaleString()} bytes JS`);

  // 2. Bundle addon-main.ts (same aliases/define as build.ts).
  const stubEmpty = join(HERE, "stubs", "empty.ts");
  const stubModule = join(HERE, "stubs", "module.ts");
  const result = await build({
    entryPoints: [join(HERE, "addon-main.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: false,
    sourcemap: false,
    alias: {
      "fs": stubEmpty,
      "path": stubEmpty,
      "stream": stubEmpty,
      "url": stubEmpty,
      "module": stubModule,
      "chrome-remote-interface": stubEmpty,
      "googleapis": stubEmpty,
      "esbuild": stubEmpty,
      "pptxgenjs": join(HERE, "stubs", "pptxgenjs-global.ts"),
      "jszip": join(HERE, "stubs", "jszip-global.ts"),
    },
    define: {
      __EXTRACT_JS_LITERAL__: JSON.stringify(extractJs),
    },
    logLevel: "info",
  });
  if (!result.outputFiles || result.outputFiles.length === 0) {
    throw new Error("esbuild produced no output");
  }
  const mainJs = result.outputFiles[0].text;
  console.log(`addon bundle → ${mainJs.length.toLocaleString()} bytes JS`);

  // 3. Vendor bundles (attach window.JSZip / window.PptxGenJS).
  //    UNLIKE the standalone page (build.ts), the add-on does NOT inline these:
  //    Apps Script's HtmlService sanitises/relays the sidebar HTML and corrupts
  //    a ~560 KB inlined minified blob (observed: "Uncaught SyntaxError: Invalid
  //    or unexpected token" → `PptxGenJS is not defined`). The sidebar is always
  //    online, so we load the vendors from a pinned CDN via <script src> (allowed
  //    in IFRAME sandbox mode) and inline only our own ~240 KB bundle.
  const JSZIP_CDN = "https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";
  const PPTX_CDN = "https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.1/dist/pptxgen.bundle.js";

  // 4. Sidebar HTML. Same dropzone UI as the standalone page, sized for the
  //    narrow Slides sidebar. google.script.run is injected by HtmlService.
  const sidebar = `<!DOCTYPE html>
<html>
<head>
<base target="_top">
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; }
  body { font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         margin: 0; padding: 12px; color: #111; }
  p.sub { color: #666; margin: 0 0 12px; font-size: 12px; }
  #dropzone { border: 2px dashed #bbb; border-radius: 10px; padding: 20px 12px;
              text-align: center; color: #555; cursor: pointer; transition: all .15s; }
  #dropzone.hover { border-color: #3b82f6; background: #eff6ff; color: #1d4ed8; }
  #dropzone strong { color: #111; }
  #picker { display: none; }
  .row { display: flex; gap: 8px; margin: 12px 0; align-items: center; flex-wrap: wrap; }
  button { padding: 7px 12px; font: inherit; border: 1px solid #ccc; background: white;
           border-radius: 6px; cursor: pointer; }
  button:disabled { opacity: .4; cursor: not-allowed; }
  button.primary { background: #2563eb; color: white; border-color: #2563eb; }
  button.primary:disabled { background: #93c5fd; border-color: #93c5fd; }
  #file-list { margin: 0; padding: 0 0 0 20px; max-height: 110px; overflow: auto;
               font: 11px/1.5 ui-monospace, monospace; color: #444; }
  #file-list li { list-style: disc; }
  #progress-wrap { height: 6px; background: #eee; border-radius: 3px; overflow: hidden; margin: 6px 0; }
  #progress-bar { height: 100%; background: #2563eb; width: 0%; transition: width .15s; }
  #progress-label { font: 11px/1 ui-monospace, monospace; color: #666; min-height: 13px; }
  #log { font: 11px/1.45 ui-monospace, monospace; background: #0b1020; color: #cbd5e1;
         padding: 8px; border-radius: 6px; height: 160px; overflow: auto; margin-top: 8px; }
  #log .warn { color: #fbbf24; }
  #log .error { color: #f87171; }
  #paste-box { width: 100%; min-height: 44px; resize: vertical; margin: 8px 0 0;
               font: 11px/1.4 ui-monospace, monospace; color: #111;
               border: 1px solid #ccc; border-radius: 6px; padding: 6px 8px; }
  #paste-box:focus { outline: none; border-color: #2563eb; box-shadow: 0 0 0 2px #bfdbfe; }
  body.dragging { outline: 3px dashed #3b82f6; outline-offset: -6px; }
  body.dragging #dropzone { border-color: #3b82f6; background: #eff6ff; color: #1d4ed8; }
  #trouble { margin: 8px 0 0; font-size: 12px; color: #666; }
  #trouble summary { cursor: pointer; }
  #notice { margin: 8px 0 0; }
  #notice .box { padding: 8px 10px; border-radius: 6px; font-size: 12px; line-height: 1.4; }
  #notice .warn { background: #fef3c7; border: 1px solid #fcd34d; color: #92400e; }
  #notice .ok { background: #dcfce7; border: 1px solid #86efac; color: #166534; }
  #notice a { color: #1d4ed8; font-weight: 600; }
</style>
</head>
<body tabindex="0">
<p class="sub">Upload, drop, or paste slide HTML. It's converted locally and inserted right after the current slide.</p>

<div id="dropzone">
  <strong>Drop .html files anywhere in this panel</strong><br>
  <span id="file-count">0</span> file(s) queued.
</div>
<input type="file" id="picker" accept=".html,.htm" multiple>

<div class="row">
  <button id="upload-btn">📂 Upload files…</button>
  <button id="paste-btn">📋 Paste from clipboard</button>
</div>

<textarea id="paste-box" placeholder="…or click here and press ⌘V / Ctrl+V to paste slide HTML"></textarea>

<ul id="file-list"></ul>

<div class="row">
  <button id="insert-btn" class="primary" disabled>Insert after current slide</button>
  <button id="clear-btn">Clear</button>
</div>

<div id="notice"></div>
<details id="trouble">
  <summary>Insert failing? (permissions)</summary>
  <div class="row">
    <button id="reauth-btn">🔐 Re-authorize</button>
    <button id="testperm-btn">🔎 Test permissions</button>
  </div>
</details>

<div id="progress-wrap"><div id="progress-bar"></div></div>
<div id="progress-label"></div>
<div id="log"></div>

<script src="${JSZIP_CDN}"></script>
<script src="${PPTX_CDN}"></script>
<script>
${mainJs}
</script>
</body>
</html>`;

  // 5. Emit the project.
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "appsscript.json"), APPSSCRIPT_JSON);
  writeFileSync(join(OUT, "Code.gs"), CODE_GS);
  writeFileSync(join(OUT, "Sidebar.html"), sidebar);

  const kb = (sidebar.length / 1024).toFixed(0);
  console.log(`\n✓ wrote Apps Script project to ${OUT}`);
  console.log(`    appsscript.json  (manifest)`);
  console.log(`    Code.gs          (${CODE_GS.length.toLocaleString()} bytes)`);
  console.log(`    Sidebar.html     (${kb} KB, bundle inlined)`);
}

main().catch((e) => {
  console.error("build-addon failed:", e);
  process.exit(1);
});
