#!/usr/bin/env npx tsx
/**
 * build-addon.ts — Bundles the Google Slides add-on (sidebar + bound Apps
 * Script) from the shared browser conversion core.
 *
 * It mirrors build.ts (same esbuild config / vendor inlining) but targets the
 * add-on instead of a standalone page. Output is a ready-to-push Apps Script
 * project under the repo-root dist/ (gitignored), mirroring the source path:
 *
 *   dist/renderer/html2slides/addon/
 *     appsscript.json   — manifest: V8, OAuth scopes (incl. external_request), Advanced Drive Service
 *     Code.gs           — server: onOpen menu + showSidebar (thin shell) + fetchExternalHtml + insertPptxAfterCurrent
 *     Sidebar.html      — fallback sidebar with the client bundle inlined (the thin-shell
 *                         showSidebar() no longer uses it; kept for offline/standalone use)
 *
 * THIN SHELL: showSidebar() now fetches /shell.html from the externally-hosted
 * Node server (addon-server) via UrlFetchApp, bakes in SERVER_ORIGIN, and serves
 * that — the heavy UI loads cross-origin from the server, so the add-on shell is
 * tiny and the UI updates without redeploying. Set SERVER_ORIGIN in Code.gs.
 *
 * Push it with clasp (`cd dist/renderer/html2slides/addon && clasp push`) or
 * paste the three files into Extensions → Apps Script. See addon/README.md.
 */
import { build, transformSync } from "esbuild";
import { execSync } from "child_process";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../../..");
const OUT = join(ROOT, "dist", "renderer", "html2slides", "addon");

function readText(p: string): string { return readFileSync(p, "utf-8"); }

// ---------------------------------------------------------------------------
// Apps Script server (Code.gs) — plain V8 JavaScript, served as a .gs file.
// ---------------------------------------------------------------------------
const CODE_GS = `/**
 * html2slides — Google Slides add-on server.
 *
 * The sidebar (Sidebar.html) builds the .pptx entirely client-side and sends
 * the bytes here as base64. We convert them to a temporary Google Slides file
 * via the Advanced Drive Service (same importer as File > Import slides), then
 * copy every slide into the active presentation right AFTER the current slide,
 * and finally delete the temp file.
 *
 * AUTOGENERATED by build-addon.ts — edit the source, not dist/Code.gs.
 */

// -----------------------------------------------------------------------------
// THIN-SHELL config. The add-on no longer inlines its UI — it fetches a small
// shell from our externally-hosted Node server (addon-server) and serves THAT
// via HtmlService. The heavy UI bundle + drawio then load cross-origin from the
// same server, so the sidebar stays tiny and updates without redeploying.
//
// !!! SET THIS to the https origin of your deployed addon-server (Caddy/TLS in
// front of it). No trailing slash. e.g. 'https://slides.your-domain.com'.
// -----------------------------------------------------------------------------
var SERVER_ORIGIN = 'https://slides.example.com';

// ── container detection: the SAME script can be bound to a Slides deck OR a
// Google Doc. Every drawio entry point routes on this instead of assuming
// SlidesApp. kind drives the Drive path: drawio/slide/<id>/ vs drawio/doc/<id>/.
function containerInfo_() {
  try {
    var p = SlidesApp.getActivePresentation();
    if (p) return { kind: 'slide', id: p.getId() };
  } catch (e) { /* not bound to Slides */ }
  try {
    var d = DocumentApp.getActiveDocument();
    if (d) return { kind: 'doc', id: d.getId() };
  } catch (e) { /* not bound to Docs */ }
  throw new Error('no active Slides presentation or Docs document');
}

function containerUi_() {
  try { var p = SlidesApp.getActivePresentation(); if (p) return SlidesApp.getUi(); } catch (e) { /* */ }
  return DocumentApp.getUi();
}

/** Exposed to the sidebar so it can adapt (e.g. hide Slides-only panels in Docs). */
function getContainerInfo() { return containerInfo_(); }

function onOpen(e) {
  // createMenu() (not createAddonMenu()) — a plain top-level menubar menu that
  // shows reliably for a container-BOUND script. createAddonMenu() is for
  // PUBLISHED Editor Add-ons and is flaky/hidden for an unpublished bound
  // script, which is why the "html2slides" menu was missing.
  //
  // CRITICAL: onOpen is a SIMPLE trigger — it runs WITHOUT data scopes, so
  // SlidesApp.getActivePresentation() / DocumentApp.getActiveDocument() THROW
  // here (they need the presentations/documents scope). Only getUi() (the
  // script.container.ui scope) is available. So we must NOT call containerInfo_/
  // containerUi_ (which probe getActive*) from onOpen — instead try each app's
  // getUi() directly and let the wrong-container one throw. The FIRST one that
  // builds the menu wins; the same script is only ever bound to one host.
  var made = false;
  try { SlidesApp.getUi().createMenu('SashaSlides').addItem('Open SashaSlides', 'showSidebar').addToUi(); made = true; } catch (e1) { /* not Slides */ }
  if (!made) { try { DocumentApp.getUi().createMenu('SashaSlides').addItem('Open SashaSlides', 'showSidebar').addToUi(); } catch (e2) { /* not Docs either */ } }
}

function onInstall(e) {
  onOpen(e);
}

function showSidebar() {
  // Thin shell: pull /shell.html from the Node server, bake the server origin
  // into its __ORIGIN__ placeholders, and serve it. The shell's own <script>
  // then fetches the full UI markup + /static/app.js cross-origin from the
  // server. UrlFetchApp here needs the script.external_request scope.
  var shell = UrlFetchApp.fetch(SERVER_ORIGIN + '/shell.html').getContentText();
  // Replace EVERY __ORIGIN__ (base href, stylesheet, fetch URLs, app.js src).
  var html = shell.split('__ORIGIN__').join(SERVER_ORIGIN);
  var out = HtmlService.createHtmlOutput(html).setTitle('SashaSlides');
  containerUi_().showSidebar(out);
}

/**
 * Fetch arbitrary HTML from an external URL on the server side (CORS-safe).
 * Backs the UI's "load HTML from external URL" control — the sidebar iframe
 * can't fetch cross-origin itself, so it relays the URL here via
 * google.script.run and gets back the raw text.
 * @param {string} url
 * @return {string} the response body
 */
function fetchExternalHtml(url) {
  return UrlFetchApp.fetch(url).getContentText();
}

/**
 * Returns the consent URL + current status so the sidebar can offer a
 * "Re-authorize" button. Apps Script does NOT re-prompt automatically once the
 * scopes are granted (the v2->v3 Drive switch added no new scope), so a manual
 * re-grant is the only way to refresh a stale/partial Drive authorization that
 * causes PERMISSION_DENIED.
 * @return {{status:string, url:string}}
 */
function getAuthInfo() {
  var info = ScriptApp.getAuthorizationInfo(ScriptApp.AuthMode.FULL);
  return { status: String(info.getAuthorizationStatus()), url: info.getAuthorizationUrl() };
}

/** Touch Drive with the user's auth so a missing/!granted drive scope throws
 * the standard authorization prompt instead of a generic storage error. Used
 * by the sidebar's "Test permissions" button. */
function testDriveAccess() {
  var about = Drive.About.get({ fields: 'user' }); // requires the drive scope
  return { ok: true, user: about && about.user ? about.user.emailAddress : '(unknown)' };
}

/**
 * Convert + insert the .pptx BEFORE or AFTER the current slide.
 * @param {string} base64  the .pptx bytes, base64-encoded
 * @param {string} title   display name for the temp converted file
 * @param {boolean} before insert before the current slide (else after)
 * @return {{inserted:number, at:number, title:string}}
 */
function insertPptx_(base64, title, before) {
  title = title || 'html2slides import';
  var blob = Utilities.newBlob(
    Utilities.base64Decode(base64),
    MimeType.MICROSOFT_POWERPOINT,
    title + '.pptx'
  );

  var tempId = null;
  try {
    // 1. Upload + convert pptx -> a temporary Google Slides file. Drive v3:
    //    uploading a blob whose target resource mimeType is a Google type
    //    converts it (the modern equivalent of the v2 convert:true flag, which
    //    Google has sunset — its failure surfaces as PERMISSION_DENIED /
    //    "server error occurred while reading from storage").
    var converted = Drive.Files.create(
      { name: title, mimeType: MimeType.GOOGLE_SLIDES },
      blob
    );
    tempId = converted.id;

    // A just-converted file can briefly 404 / PERMISSION_DENIED before its
    // storage settles; retry openById a few times with a short backoff.
    var src = null;
    for (var attempt = 0; attempt < 5; attempt++) {
      try { src = SlidesApp.openById(tempId); break; }
      catch (openErr) {
        if (attempt === 4) throw openErr;
        Utilities.sleep(600);
      }
    }
    var srcSlides = src.getSlides();
    if (!srcSlides.length) throw new Error('converted deck had no slides');

    var pres = SlidesApp.getActivePresentation();
    var slides = pres.getSlides();

    // 2. Where is the current slide? Insert before/after it; fall back to the end.
    var insertAt = slides.length;
    var sel = pres.getSelection();
    var cur = sel ? sel.getCurrentPage() : null;
    if (cur) {
      var curId = cur.getObjectId();
      for (var i = 0; i < slides.length; i++) {
        if (slides[i].getObjectId() === curId) { insertAt = before ? i : i + 1; break; }
      }
    }

    // 3. Copy each source slide (with formatting) into the active deck.
    var firstAt = insertAt;
    for (var j = 0; j < srcSlides.length; j++) {
      pres.insertSlide(insertAt++, srcSlides[j]);
    }

    return { inserted: srcSlides.length, at: firstAt + 1, title: title };
  } finally {
    // 4. Best-effort cleanup of the temp file.
    if (tempId) {
      try { Drive.Files.remove(tempId); } catch (err) { /* leave it in Trash */ }
    }
  }
}

function insertPptxAfterCurrent(base64, title)  { return insertPptx_(base64, title, false); }
function insertPptxBeforeCurrent(base64, title) { return insertPptx_(base64, title, true); }

/** Parse "1-5, 8, 11-13" -> {idx:true} (1-based); blank -> null = all slides. */
function parseRange_(range) {
  if (range == null) return null;
  var trimmed = String(range).trim();
  if (trimmed === '') return null;
  var out = {};
  var segs = trimmed.split(',');
  for (var i = 0; i < segs.length; i++) {
    var seg = segs[i].trim();
    if (seg === '') continue;
    var dash = seg.indexOf('-');
    if (dash === -1) {
      var n = Number(seg);
      if (!(n >= 1) || Math.floor(n) !== n) throw new Error('bad slide index "' + seg + '"');
      out[n] = true;
    } else {
      var a = Number(seg.slice(0, dash).trim());
      var b = Number(seg.slice(dash + 1).trim());
      if (!(a >= 1) || !(b >= 1) || Math.floor(a) !== a || Math.floor(b) !== b) throw new Error('bad slide range "' + seg + '"');
      var lo = Math.min(a, b), hi = Math.max(a, b);
      for (var k = lo; k <= hi; k++) out[k] = true;
    }
  }
  return out;
}

/**
 * Fetch a Slides REST URL with the user's OAuth, turning the API-not-enabled 403
 * into an actionable message (with the exact console URL to click). The Slides
 * API must be enabled in the script's GCP project — the manifest declares the
 * Slides advanced service so Apps Script auto-enables it, but a script that was
 * authorised before that manifest landed still needs a one-time manual enable.
 */
function slidesFetch_(url, auth) {
  var resp = UrlFetchApp.fetch(url, auth);
  var code = resp.getResponseCode();
  var text = resp.getContentText();
  if (code === 200) return text;
  if (code === 403) {
    // Google's "API not enabled" body embeds the EXACT console URL for the right
    // project — extract it verbatim (reconstructing it ourselves risks pointing at
    // the wrong project, which silently enables nothing). The cleaner fix is to
    // paste the manifest declaring the Slides advanced service (auto-enables the API).
    var m = text.match(/https?:\\/\\/console\\.(?:developers|cloud)\\.google\\.com\\/[^\\s"'\\\\]+/);
    if (m) {
      throw new Error('The Google Slides API is not enabled for this add-on\\u2019s Google ' +
        'Cloud project. EITHER re-paste the manifest (Project Settings \\u2192 appsscript.json) ' +
        'which auto-enables it, OR open this exact link, click ENABLE, wait ~2 min, then retry ' +
        'Export (don\\u2019t switch projects in the console):\\n' + m[0]);
    }
    throw new Error('Slides API permission error (403): ' + text.slice(0, 400));
  }
  throw new Error('Slides API request failed (' + code + '): ' + text.slice(0, 400));
}

/**
 * Export the active deck's slides as a PNG zip, using the signed-in user's OAuth
 * (getThumbnail PNG → Utilities.zip → base64). payload: { range?, excludeHidden? }.
 * @return {{filename:string, mimeType:string, base64:string}}
 */
function exportSlidesZip(payload) {
  payload = payload || {};
  var presentationId = payload.presentationId || SlidesApp.getActivePresentation().getId();
  var included = parseRange_(payload.range);
  var wantExcludeHidden = payload.excludeHidden === true;

  var token = ScriptApp.getOAuthToken();
  var auth = { headers: { Authorization: 'Bearer ' + token }, muteHttpExceptions: true };
  var base = 'https://slides.googleapis.com/v1/presentations/' + encodeURIComponent(presentationId);

  var meta = JSON.parse(slidesFetch_(base + '?fields=slides(objectId,slideProperties/isSkipped)', auth));
  var slides = meta.slides || [];
  var blobs = [];
  for (var i = 0; i < slides.length; i++) {
    var oneBased = i + 1;
    if (included && !included[oneBased]) continue;
    var sp = slides[i].slideProperties || {};
    if (wantExcludeHidden && sp.isSkipped === true) continue;
    var slideId = slides[i].objectId;
    if (!slideId) continue;
    var thumbUrl = base + '/pages/' + encodeURIComponent(slideId) +
      '/thumbnail?thumbnailProperties.mimeType=PNG&thumbnailProperties.thumbnailSize=LARGE';
    var contentUrl = JSON.parse(slidesFetch_(thumbUrl, auth)).contentUrl;
    if (!contentUrl) continue;
    var nn = (oneBased < 10 ? '0' : '') + oneBased;
    blobs.push(UrlFetchApp.fetch(contentUrl).getBlob().setName('slide_' + nn + '.png'));
  }
  if (blobs.length === 0) throw new Error('no slides matched the requested range/filter');
  var zipBlob = Utilities.zip(blobs, 'slides.zip');
  return { filename: 'slides.zip', mimeType: 'application/zip', base64: Utilities.base64Encode(zipBlob.getBytes()) };
}

/** Deck state for the bridge: total slides, current (1-based, 0 if none) and the
 *  1-based indices of skipped (hidden) slides. */
function getDeckState() {
  var pres = SlidesApp.getActivePresentation();
  var slides = pres.getSlides();
  var auth = { headers: { Authorization: 'Bearer ' + ScriptApp.getOAuthToken() }, muteHttpExceptions: true };
  var base = 'https://slides.googleapis.com/v1/presentations/' + encodeURIComponent(pres.getId());
  var meta = JSON.parse(slidesFetch_(base + '?fields=slides(objectId,slideProperties/isSkipped)', auth));
  var ms = meta.slides || [];
  var skipped = [];
  for (var i = 0; i < ms.length; i++) {
    var sp = ms[i].slideProperties || {};
    if (sp.isSkipped === true) skipped.push(i + 1);
  }
  var current = 0, curId = null;
  try { var sel = pres.getSelection(); var page = sel ? sel.getCurrentPage() : null; if (page) curId = page.getObjectId(); } catch (e) {}
  if (curId) { for (var j = 0; j < slides.length; j++) { if (slides[j].getObjectId() === curId) { current = j + 1; break; } } }
  return { ok: true, count: slides.length, current: current, skipped: skipped };
}

/** Screenshot one or more slides as PNG. payload: { range?, indices?[], includeXml? }.
 *  Default = the current slide. Returns { ok, slides:[{index, skipped, png, xml?}] }.
 *  png is a data: URL. xml (only when includeXml) is the slide's OpenXML from a
 *  best-effort .pptx export — null if it couldn't be resolved. */
function screenshotSlides(payload) {
  payload = payload || {};
  var pres = SlidesApp.getActivePresentation();
  var auth = { headers: { Authorization: 'Bearer ' + ScriptApp.getOAuthToken() }, muteHttpExceptions: true };
  var base = 'https://slides.googleapis.com/v1/presentations/' + encodeURIComponent(pres.getId());
  var meta = JSON.parse(slidesFetch_(base + '?fields=slides(objectId,slideProperties/isSkipped)', auth));
  var ms = meta.slides || [];

  var want = {};
  if (payload.indices && payload.indices.length) {
    for (var a = 0; a < payload.indices.length; a++) want[payload.indices[a]] = true;
  } else if (payload.range != null && String(payload.range).trim() !== '') {
    want = parseRange_(payload.range) || {};
  } else {
    want[getDeckState().current || ms.length] = true;
  }

  var xmlByIndex = payload.includeXml === true ? slideXmlMap_(pres.getId(), auth) : null;
  var out = [];
  for (var k = 0; k < ms.length; k++) {
    var oneBased = k + 1;
    if (!want[oneBased]) continue;
    var sp2 = ms[k].slideProperties || {};
    var entry = { index: oneBased, skipped: sp2.isSkipped === true, png: '' };
    var thumb = base + '/pages/' + encodeURIComponent(ms[k].objectId) +
      '/thumbnail?thumbnailProperties.mimeType=PNG&thumbnailProperties.thumbnailSize=LARGE';
    var contentUrl = JSON.parse(slidesFetch_(thumb, auth)).contentUrl;
    if (contentUrl) {
      var blob = UrlFetchApp.fetch(contentUrl).getBlob();
      entry.png = 'data:image/png;base64,' + Utilities.base64Encode(blob.getBytes());
    }
    if (xmlByIndex) entry.xml = xmlByIndex[oneBased] || null;
    out.push(entry);
  }
  if (out.length === 0) throw new Error('no slides matched the requested range/indices');
  return { ok: true, slides: out };
}

function between_(s, a, b) {
  var i = s.indexOf(a); if (i === -1) return '';
  i += a.length; var j = s.indexOf(b, i); return j === -1 ? '' : s.substring(i, j);
}

/** Best-effort map of 1-based slide order -> slide OpenXML, from a .pptx export.
 *  Resolves order via presentation.xml sldIdLst + its rels. Returns {} on failure. */
function slideXmlMap_(presId, auth) {
  try {
    var url = 'https://www.googleapis.com/drive/v3/files/' + encodeURIComponent(presId) +
      '/export?mimeType=application%2Fvnd.openxmlformats-officedocument.presentationml.presentation';
    var files = Utilities.unzip(UrlFetchApp.fetch(url, auth).getBlob());
    var byName = {};
    for (var i = 0; i < files.length; i++) byName[files[i].getName()] = files[i];
    var presXml = byName['ppt/presentation.xml'] ? byName['ppt/presentation.xml'].getDataAsString() : '';
    var rels = byName['ppt/_rels/presentation.xml.rels'] ? byName['ppt/_rels/presentation.xml.rels'].getDataAsString() : '';
    var ridTarget = {};
    var rp = rels.split('<Relationship');
    for (var r = 1; r < rp.length; r++) {
      var id = between_(rp[r], ' Id="', '"'), tgt = between_(rp[r], ' Target="', '"');
      if (id && tgt) ridTarget[id] = tgt;
    }
    var lst = between_(presXml, '<p:sldIdLst', '</p:sldIdLst>');
    var map = {}, n = 0, sp = lst.split('<p:sldId');
    for (var s = 1; s < sp.length; s++) {
      var rid = between_(sp[s], 'r:id="', '"');
      if (!rid) continue;
      n++;
      var name = (ridTarget[rid] || '').replace('../', '');
      if (name.indexOf('ppt/') !== 0) name = 'ppt/' + name;
      var f = byName[name] || byName['ppt/slides/' + name.split('/').pop()];
      if (f) map[n] = f.getDataAsString();
    }
    return map;
  } catch (e) { return {}; }
}

// ── drawio ⇄ Drive (Phase 2) ─────────────────────────────────────────────────
// A diagram's editable source lives on Google Drive as
// drawio/<slide|doc>/<containerId>/<diagramId>.drawio.svg — an SVG whose root
// carries the mxfile XML in its content= attribute (drawio's own editable-SVG
// convention). The on-slide/in-doc IMAGE links to that Drive file; detection is
// purely "image link URL resolves to a *.drawio(.svg|.png)? file". The old
// off-canvas magenta XML box is retired (no writer remains; convert-pptx now
// links the imported image to Drive in its post-upload pass).

var DRAWIO_EXT_RE = /\\.drawio(\\.svg|\\.png)?$/i;

/** Drive fileId from a drive.google.com URL (file/d/<id>/… or open?id=<id>). */
function drawioFileIdFromUrl_(url) {
  var m = String(url || '').match(/\\/file\\/d\\/([A-Za-z0-9_-]+)/) ||
          String(url || '').match(/[?&]id=([A-Za-z0-9_-]+)/);
  return m ? m[1] : null;
}

/** If the image links to a drawio file, return {url, fileId, name}; else null.
 *  Works for both Slides images (getLink().getUrl()) and Docs inline images
 *  (getLinkUrl()). A plain non-Drive URL counts iff its path ends in a drawio
 *  extension (fileId stays null — read-only detection, no write-back). */
function imageDrawioLink_(img) {
  var url = null;
  try { var l = img.getLink && img.getLink(); url = l ? l.getUrl() : null; } catch (e) { /* */ }
  if (!url) { try { url = img.getLinkUrl && img.getLinkUrl(); } catch (e) { /* */ } }
  if (!url) return null;
  var fileId = drawioFileIdFromUrl_(url);
  if (!fileId) return DRAWIO_EXT_RE.test(url.split('?')[0]) ? { url: url, fileId: null, name: url.split('?')[0].split('/').pop() } : null;
  try {
    var f = DriveApp.getFileById(fileId);
    var name = f.getName();
    return DRAWIO_EXT_RE.test(name) ? { url: url, fileId: fileId, name: name } : null;
  } catch (e) { return null; }  // dangling link / no access → not editable
}

/** Read a drawio Drive file's EXACT bytes for the editor to open — no hand
 *  unwrapping. drawio's own loader extracts the diagram (verified: the load
 *  action with a raw editable .drawio.svg round-trips), so we hand it verbatim:
 *    .drawio.svg / .drawio → the raw text (SVG with content= attr, or mxfile)
 *    .drawio.png           → a data:image/png URI (drawio load handles xmlpng)
 *  The editor wrapper picks the load form by sniffing the returned string. */
function drawioFileData_(fileId, name) {
  var f = DriveApp.getFileById(fileId);
  if (/\\.drawio\\.png$/i.test(name)) {
    var b = f.getBlob();
    return 'data:' + (b.getContentType() || 'image/png') + ';base64,' + Utilities.base64Encode(b.getBytes());
  }
  return f.getBlob().getDataAsString();   // .drawio.svg or .drawio → verbatim text
}

/** Minimal editable SVG when the editor didn't hand us a rendered xmlsvg. */
function buildEditableSvg_(xml) {
  var esc = String(xml).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  return '<svg xmlns="http://www.w3.org/2000/svg" content="' + esc + '"/>';
}

/** Idempotently resolve/create drawio/<kind>/<containerId>/ under My Drive. */
function ensureDrawioFolder_(kind, containerId) {
  var folder = DriveApp.getRootFolder();
  var segs = ['drawio', kind, containerId];
  for (var i = 0; i < segs.length; i++) {
    var it = folder.getFoldersByName(segs[i]);
    folder = it.hasNext() ? it.next() : folder.createFolder(segs[i]);
  }
  return folder;
}

/** Create-or-update <diagramId>.drawio.svg in the container's drawio folder.
 *  Returns {fileId, url} — url is what the image link points at. */
function writeDrawioDriveFile_(kind, containerId, diagramId, svgContent) {
  var folder = ensureDrawioFolder_(kind, containerId);
  var name = diagramId + '.drawio.svg';
  var it = folder.getFilesByName(name);
  var file = it.hasNext() ? it.next().setContent(svgContent)
                          : folder.createFile(name, svgContent, 'image/svg+xml');
  return { fileId: file.getId(), url: file.getUrl() };
}

/** drawio: enumerate the container's diagrams — every image whose LINK resolves
 *  to a *.drawio(.svg|.png)? file. XML is loaded from Drive server-side (except
 *  .drawio.png, where the client falls back to the PNG-chunk detector).
 *  Container-agnostic: Slides deck or Google Doc. Returns
 *  [{id, slideIndex?, name, dataUrl, box?, xml, driveFileId, driveName}]. */
function listDeckImages() {
  var info = containerInfo_();
  var out = [];
  if (info.kind === 'slide') {
    var pres = SlidesApp.getActivePresentation();
    var slides = pres.getSlides();
    var pw = pres.getPageWidth(), ph = pres.getPageHeight();
    for (var s = 0; s < slides.length; s++) {
      var images = slides[s].getImages();
      for (var i = 0; i < images.length; i++) {
        var img = images[i];
        var dl = imageDrawioLink_(img);
        if (!dl) continue;
        var blob = img.getBlob();
        out.push({
          id: img.getObjectId(),
          slideIndex: s + 1,
          name: dl.name || ('Diagram \\u2014 slide ' + (s + 1)),
          dataUrl: 'data:' + (blob.getContentType() || 'image/png') + ';base64,' + Utilities.base64Encode(blob.getBytes()),
          // current frame as NORMALIZED [0,1] slide coords, so the agent can reason about layout
          box: { x: img.getLeft() / pw, y: img.getTop() / ph, w: img.getWidth() / pw, h: img.getHeight() / ph },
          xml: dl.fileId ? drawioFileData_(dl.fileId, dl.name) : null,
          driveFileId: dl.fileId,
          driveName: dl.name,
        });
      }
    }
    return out;
  }
  // Google Doc: inline images in the body, same link-based detection.
  var body = DocumentApp.getActiveDocument().getBody();
  var imgs = body.getImages();
  for (var d = 0; d < imgs.length; d++) {
    var dimg = imgs[d];
    var ddl = imageDrawioLink_(dimg);
    if (!ddl) continue;
    var dblob = dimg.getBlob();
    out.push({
      id: 'doc-img-' + d,               // Docs images have no objectId; index-addressed
      docImageIndex: d,
      name: ddl.name || ('Diagram ' + (d + 1)),
      dataUrl: 'data:' + (dblob.getContentType() || 'image/png') + ';base64,' + Utilities.base64Encode(dblob.getBytes()),
      box: null,
      xml: ddl.fileId ? drawioFileData_(ddl.fileId, ddl.name) : null,
      driveFileId: ddl.fileId,
      driveName: ddl.name,
    });
  }
  return out;
}

/** Decode a data:URL (or bare base64) into an Apps Script Blob. */
function dataUrlToBlob_(dataUrl, name) {
  var comma = dataUrl.indexOf(',');
  var header = comma >= 0 ? dataUrl.substring(0, comma) : '';
  var b64 = comma >= 0 ? dataUrl.substring(comma + 1) : dataUrl;
  var ct = (header.match(/data:([^;]+)/) || [])[1] || 'image/png';
  return Utilities.newBlob(Utilities.base64Decode(b64), ct, name || 'diagram.png');
}

/** Locate a Slides image by its object id across every slide. */
function findImageById_(objectId) {
  var slides = SlidesApp.getActivePresentation().getSlides();
  for (var s = 0; s < slides.length; s++) {
    var images = slides[s].getImages();
    for (var i = 0; i < images.length; i++) {
      if (images[i].getObjectId() === objectId) return images[i];
    }
  }
  return null;
}

/** The current (selected) slide, falling back to the last slide. */
function currentSlide_(pres) {
  try {
    var sel = pres.getSelection();
    var page = sel ? sel.getCurrentPage() : null;
    if (page && page.asSlide) return page.asSlide();
  } catch (e) { /* no selection (headless) */ }
  var slides = pres.getSlides();
  return slides[slides.length - 1];
}

/** Replace an existing diagram image's bytes (drawio "Save" → new xmlpng). */
function replaceImage(objectId, dataUrl) {
  var img = findImageById_(objectId);
  if (!img) throw new Error('image not found: ' + objectId);
  img.replace(dataUrlToBlob_(dataUrl, 'diagram.png'));
  return { ok: true, id: objectId };
}

/** Insert a brand-new diagram image on the current (or last) slide. */
function insertImage(dataUrl) {
  var pres = SlidesApp.getActivePresentation();
  var image = currentSlide_(pres).insertImage(dataUrlToBlob_(dataUrl, 'diagram.png'));
  return { ok: true, id: image.getObjectId() };
}

/** Delete a diagram image by object id. */
function deleteImage(objectId) {
  var img = findImageById_(objectId);
  if (!img) throw new Error('image not found: ' + objectId);
  img.remove();
  return { ok: true };
}

/** HTML-escape (for seeding XML into a hidden textarea — safe vs </script>). */
function htmlEscape_(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Open the self-hosted drawio editor BIG, in a modal dialog (the sidebar is too
 *  narrow). The dialog hosts the editor iframe full-size, seeds the diagram XML,
 *  and on Save exports an xmlpng → replaceImage (existing) or insertImage (new),
 *  then closes. payload: { xml?, imageId? }. */
function showDrawioDialog(payload) {
  payload = payload || {};
  var xml = payload.xml || '';
  var imageId = payload.imageId || '';
  var diagramId = payload.diagramId || '';
  // Hide ALL of drawio's own buttons (noSaveBtn=1 & saveAndExit=0 & noExitBtn=1) —
  // its Save routes through an export SERVER we don't host. We drive save ourselves
  // via the client-side {action:'export'} message, triggered by our own toolbar.
  var src = SERVER_ORIGIN + '/drawio/?embed=1&proto=json&spin=1&libraries=1' +
    '&noSaveBtn=1&saveAndExit=0&noExitBtn=1';
  var html = '' +
    '<!doctype html><html><head><meta charset="utf-8">' +
    // Flexbox column (NOT position:fixed — fixed collapses inside Google's
    // IFRAME_SANDBOX; height:100% + flex fills reliably).
    '<style>html,body{margin:0;padding:0;height:100%;overflow:hidden;font:13px Roboto,Arial,sans-serif}' +
    'body{display:flex;flex-direction:column}' +
    '#bar{flex:0 0 44px;display:flex;align-items:center;gap:8px;' +
    'padding:0 12px;background:#f1f3f4;border-bottom:1px solid #dadce0;box-sizing:border-box}' +
    '#bar button{font:inherit;padding:7px 16px;border-radius:4px;border:1px solid #dadce0;cursor:pointer;background:#fff}' +
    '#bar .save{background:#1a73e8;color:#fff;border-color:#1a73e8;font-weight:600}' +
    '#bar button:disabled{opacity:.6;cursor:progress}' +
    '#msg{color:#5f6368}' +
    '#f{flex:1 1 auto;width:100%;border:0;display:block}' +
    '</style></head><body>' +
    '<div id="bar"><button class="save" id="saveBtn">Save &amp; Close</button>' +
    '<button id="cancelBtn">Cancel</button><span id="msg"></span></div>' +
    '<textarea id="seed" style="display:none">' + htmlEscape_(xml) + '</textarea>' +
    '<iframe id="f" src="' + src + '"></iframe>' +
    '<' + 'script>' +
    'var XML=document.getElementById("seed").value;' +
    'var IMAGE_ID=' + JSON.stringify(imageId) + ';' +
    'var DIAGRAM_ID=' + JSON.stringify(diagramId) + ';' +
    'var frame=document.getElementById("f");' +
    'var saveBtn=document.getElementById("saveBtn");' +
    'var saving=false;var pendingPng=null;' +
    'function setMsg(t){document.getElementById("msg").textContent=t||""}' +
    'function post(o){try{frame.contentWindow.postMessage(JSON.stringify(o),"*")}catch(e){}}' +
    'function done(){google.script.host.close()}' +
    'document.getElementById("cancelBtn").onclick=done;' +
    // Our Save: TWO exports — a high-res xmlpng for the slide image (rendered
    // client-side; scale:4 → 5120x2880 for a 1280x720 diagram), then an xmlsvg
    // (rendered editable SVG) that saveDiagram writes to the Drive-side
    // <diagramId>.drawio.svg. drawio replies {event:"export",format,data,xml}.
    'saveBtn.onclick=function(){if(saving)return;saving=true;saveBtn.disabled=true;setMsg("Exporting\\u2026");' +
    'pendingPng=null;post({action:"export",format:"xmlpng",scale:4,spin:"Exporting\\u2026"})};' +
    'function commit(png,svg,xml){var err=function(e){saving=false;saveBtn.disabled=false;setMsg("");' +
    'alert("Save failed: "+((e&&e.message)||e))};setMsg("Saving\\u2026");' +
    'google.script.run.withSuccessHandler(done).withFailureHandler(err)' +
    '.saveDiagram({imageId:IMAGE_ID,diagramId:DIAGRAM_ID,png:png,svg:svg,xml:xml})}' +
    'window.addEventListener("message",function(ev){var m=ev.data;if(typeof m!=="string")return;' +
    'try{m=JSON.parse(m)}catch(e){return}' +
    'if(m.event==="init"){post({action:"load",xml:XML,autosave:1})}' +
    'else if(m.event==="export"){' +
    'if(pendingPng===null){pendingPng=m.data;setMsg("Exporting SVG\\u2026");' +
    'post({action:"export",format:"xmlsvg",spin:"Exporting\\u2026"})}' +
    'else{commit(pendingPng,m.data,m.xml||XML)}}' +
    'else if(m.event==="exit"){if(!saving)done()}});' +
    '</' + 'script></body></html>';
  var out = HtmlService.createHtmlOutput(html).setWidth(1600).setHeight(1000);
  SlidesApp.getUi().showModalDialog(out, 'drawio editor');
  return { ok: true };
}

/** Save an edited diagram: replace (or insert) the rendered PNG AND write the
 *  editable source back to its Drive file (drawio/<kind>/<containerId>/
 *  <diagramId>.drawio.svg), so reopening loads the edited version from Drive.
 *  payload: { imageId?, png (dataUrl), xml, svg? (dataUrl or raw editable SVG,
 *  preferred — a RENDERED editable SVG from the editor's xmlsvg export),
 *  diagramId? (REQUIRED for a new diagram — the Drive file name), slide?,
 *  x/y/w/h? }. */
function saveDiagram(payload) {
  payload = payload || {};
  var info = containerInfo_();
  var blob = dataUrlToBlob_(payload.png || '', 'diagram.png');
  var xml = payload.xml || '';
  var imageId = payload.imageId || '';
  var svgContent = svgPayloadToString_(payload.svg) || (xml ? buildEditableSvg_(xml) : '');

  if (info.kind === 'doc') return saveDocDiagram_(info, blob, xml, svgContent, payload);

  var pres = SlidesApp.getActivePresentation();
  var hasPos = (payload.x != null || payload.y != null || payload.w != null || payload.h != null);
  if (imageId) {
    var entry = findImageEntry_(imageId);
    if (!entry) throw new Error('image not found: ' + imageId);
    // Read the Drive target BEFORE replace() — replacing bytes keeps the link,
    // but read first so a legacy unlinked image gets a fresh file + link below.
    var dl = imageDrawioLink_(entry.image);
    entry.image.replace(blob);
    if (svgContent) {
      if (dl && dl.fileId) {
        DriveApp.getFileById(dl.fileId).setContent(svgContent);
      } else {
        // Legacy image without a drawio link (pre-Phase-2 deck): promote it —
        // create the Drive file and set the link so it round-trips from now on.
        var promoted = writeDrawioDriveFile_('slide', info.id,
          payload.diagramId || ('slide' + slideIndexOf_(pres, entry.slide) + '_' + Utilities.getUuid().slice(0, 8)),
          svgContent);
        entry.image.setLinkUrl(promoted.url);
      }
    }
    if (hasPos) placeDiagram_(pres, entry.image, payload); // only move/resize when asked
    return { ok: true, id: imageId, slide: slideIndexOf_(pres, entry.slide) };
  }
  // new diagram: diagramId names the Drive file (the sidebar asks the user)
  if (!payload.diagramId) throw new Error('saveDiagram: diagramId is required for a new diagram');
  var slides = pres.getSlides();
  var slide = (payload.slide && payload.slide >= 1 && payload.slide <= slides.length)
    ? slides[payload.slide - 1] : currentSlide_(pres);
  var image = slide.insertImage(blob);
  var res = writeDrawioDriveFile_('slide', info.id, payload.diagramId, svgContent || buildEditableSvg_(xml));
  image.setLinkUrl(res.url);
  placeDiagram_(pres, image, payload);                     // fit/center by default, or explicit
  return { ok: true, id: image.getObjectId(), slide: slideIndexOf_(pres, slide), driveFileId: res.fileId };
}

/** payload.svg may be a data:image/svg+xml dataUrl (editor xmlsvg export) or a
 *  raw '<svg…' string. Normalize to the raw SVG text (or null). */
function svgPayloadToString_(svg) {
  if (!svg) return null;
  var s = String(svg);
  if (s.slice(0, 5) === 'data:') {
    var comma = s.indexOf(',');
    var body = comma >= 0 ? s.substring(comma + 1) : '';
    if (/;base64/.test(s.substring(0, comma))) return Utilities.newBlob(Utilities.base64Decode(body)).getDataAsString();
    return decodeURIComponent(body);
  }
  return s.slice(0, 4) === '<svg' || s.indexOf('<svg') >= 0 ? s : null;
}

/** Docs half of saveDiagram: replace an inline image (Docs has no replace() —
 *  insert the new image at the same child index, copy size, remove the old one)
 *  or append a new one at the cursor/end. Drive write-back identical to Slides
 *  but under drawio/doc/<docId>/. */
function saveDocDiagram_(info, blob, xml, svgContent, payload) {
  var doc = DocumentApp.getActiveDocument();
  var body = doc.getBody();
  var imageId = payload.imageId || '';
  if (imageId) {
    var idx = parseInt(String(imageId).replace('doc-img-', ''), 10);
    var imgs = body.getImages();
    if (!(idx >= 0 && idx < imgs.length)) throw new Error('doc image not found: ' + imageId);
    var old = imgs[idx];
    var dl = imageDrawioLink_(old);
    var w = old.getWidth(), h = old.getHeight();
    var para = old.getParent();
    var childIdx = para.getChildIndex(old);
    var fresh = para.asParagraph().insertInlineImage(childIdx + 1, blob);
    old.removeFromParent();
    fresh.setWidth(w).setHeight(h);
    if (svgContent) {
      if (dl && dl.fileId) {
        DriveApp.getFileById(dl.fileId).setContent(svgContent);
        fresh.setLinkUrl(dl.url);
      } else {
        var promoted = writeDrawioDriveFile_('doc', info.id,
          payload.diagramId || ('diagram_' + Utilities.getUuid().slice(0, 8)), svgContent);
        fresh.setLinkUrl(promoted.url);
      }
    } else if (dl) {
      fresh.setLinkUrl(dl.url);
    }
    return { ok: true, id: imageId };
  }
  if (!payload.diagramId) throw new Error('saveDiagram: diagramId is required for a new diagram');
  var cursor = doc.getCursor();
  var image = cursor
    ? cursor.insertInlineImage(blob)
    : body.appendParagraph('').appendInlineImage(blob);
  if (!image) image = body.appendParagraph('').appendInlineImage(blob);
  var res = writeDrawioDriveFile_('doc', info.id, payload.diagramId, svgContent || buildEditableSvg_(xml));
  image.setLinkUrl(res.url);
  return { ok: true, id: 'doc-img-' + (body.getImages().length - 1), driveFileId: res.fileId };
}

/** Position/size a diagram image. x,y,w,h are NORMALIZED slide coordinates in
 *  [0,1] (x,y = top-left fraction of the page; w,h = fraction of page size). With
 *  none given, fit the image to ~80% of the page preserving its aspect and center
 *  it (sane default vs the raw native size, which overflows the slide). Any
 *  provided field overrides. Only the image moves — the off-canvas XML source box
 *  below the slide is left untouched. */
function placeDiagram_(pres, image, p) {
  var pw = pres.getPageWidth(), ph = pres.getPageHeight();
  var natW = image.getWidth(), natH = image.getHeight();
  var fit = Math.min(pw * 0.8 / natW, ph * 0.8 / natH);
  var w = (p.w != null) ? p.w * pw : natW * fit;
  var h = (p.h != null) ? p.h * ph : natH * fit;
  image.setWidth(w).setHeight(h);
  image.setLeft((p.x != null) ? p.x * pw : (pw - w) / 2);
  image.setTop((p.y != null) ? p.y * ph : (ph - h) / 2);
}

/** 1-based index of a slide in the deck (for reporting back where it landed). */
function slideIndexOf_(pres, slide) {
  var slides = pres.getSlides(), id = slide.getObjectId();
  for (var i = 0; i < slides.length; i++) if (slides[i].getObjectId() === id) return i + 1;
  return null;
}

/** Like findImageById_ but also returns the slide the image is on. */
function findImageEntry_(objectId) {
  var slides = SlidesApp.getActivePresentation().getSlides();
  for (var s = 0; s < slides.length; s++) {
    var images = slides[s].getImages();
    for (var i = 0; i < images.length; i++) {
      if (images[i].getObjectId() === objectId) return { image: images[i], slide: slides[s] };
    }
  }
  return null;
}

/** The currently SELECTED drawio image, or null. Backs the sidebar's
 *  selection poller: select a picture whose link ends in .drawio(.svg|.png) →
 *  the panel offers/loads it for editing. Slides only — Docs has no image
 *  selection API, so the panel falls back to its list there. */
function getSelectedDrawio() {
  var info = containerInfo_();
  if (info.kind !== 'slide') return null;
  var pres = SlidesApp.getActivePresentation();
  var sel;
  try { sel = pres.getSelection(); } catch (e) { return null; }
  if (!sel) return null;
  var range = sel.getPageElementRange();
  if (!range) return null;
  var els = range.getPageElements();
  for (var i = 0; i < els.length; i++) {
    var el = els[i];
    var img;
    try { img = el.asImage(); } catch (e) { continue; }
    if (!img) continue;
    var dl = imageDrawioLink_(img);
    if (!dl) continue;
    return {
      id: img.getObjectId(),
      name: dl.name,
      driveFileId: dl.fileId,
      xml: dl.fileId ? drawioFileData_(dl.fileId, dl.name) : null,
    };
  }
  return null;
}
`;

// ---------------------------------------------------------------------------
// Apps Script manifest. Full presentations + drive scopes are needed because
// we openById() a *separate* converted file and write into the active deck;
// the Advanced Drive Service (v3) provides the pptx->Slides conversion (upload
// a blob with a Google target mimeType). v2's convert flag has been sunset.
// ---------------------------------------------------------------------------
const APPSSCRIPT_JSON = JSON.stringify({
  timeZone: "Etc/UTC",
  exceptionLogging: "STACKDRIVER",
  runtimeVersion: "V8",
  oauthScopes: [
    "https://www.googleapis.com/auth/presentations",
    // Docs container support (drawio side panel in Google Docs — the same
    // script can be bound to a Doc; containerInfo_() routes on the host).
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/script.container.ui",
    // UrlFetchApp — showSidebar() fetches the thin shell from the Node server
    // and fetchExternalHtml() relays external URLs for the UI (CORS-safe path).
    "https://www.googleapis.com/auth/script.external_request",
  ],
  dependencies: {
    enabledAdvancedServices: [
      { userSymbol: "Drive", serviceId: "drive", version: "v3" },
      // Declaring the Slides advanced service makes Apps Script auto-enable the
      // Slides API in the script's GCP project, so exportSlidesZip's getThumbnail
      // REST calls (via UrlFetchApp) aren't 403'd on a fresh deploy.
      { userSymbol: "Slides", serviceId: "slides", version: "v1" },
    ],
  },
}, null, 2);

async function main() {
  // 1. Compile extract-dom.ts -> JS string (same as build.ts).
  const extractTs = readText(join(HERE, "..", "extract-dom.ts"));
  const extractJs = transformSync(extractTs, { loader: "ts", target: "es2020" }).code;
  console.log(`extract-dom.ts → ${extractJs.length.toLocaleString()} bytes JS`);

  // 2. Bundle addon-main.ts (same aliases/define as build.ts).
  const stubEmpty = join(HERE, "stubs", "empty.ts");
  const stubModule = join(HERE, "stubs", "module.ts");
  const result = await build({
    entryPoints: [join(HERE, "addon-main.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: false,
    sourcemap: false,
    alias: {
      "fs": stubEmpty,
      "path": stubEmpty,
      "stream": stubEmpty,
      "url": stubEmpty,
      "module": stubModule,
      "chrome-remote-interface": stubEmpty,
      "googleapis": stubEmpty,
      "esbuild": stubEmpty,
      "pptxgenjs": join(HERE, "stubs", "pptxgenjs-global.ts"),
      "jszip": join(HERE, "stubs", "jszip-global.ts"),
    },
    define: {
      __EXTRACT_JS_LITERAL__: JSON.stringify(extractJs),
    },
    logLevel: "info",
  });
  if (!result.outputFiles || result.outputFiles.length === 0) {
    throw new Error("esbuild produced no output");
  }
  const mainJs = result.outputFiles[0].text;
  console.log(`addon bundle → ${mainJs.length.toLocaleString()} bytes JS`);

  // 2b. Bundle insert-feature.ts → addon-server/public/convert-bundle.js (same
  //     esbuild config: stubs + window globals for pptxgenjs/jszip + the inlined
  //     extract-dom blob). This is what gives the SERVER-HOSTED UI its
  //     bridge.insert(position): convert HTML→pptx in-browser, then google.script.run.
  const convResult = await build({
    entryPoints: [join(HERE, "insert-feature.ts")],
    bundle: true, write: false, format: "iife", platform: "browser", target: "es2020",
    minify: false, sourcemap: false,
    alias: {
      "fs": stubEmpty, "path": stubEmpty, "stream": stubEmpty, "url": stubEmpty,
      "module": stubModule, "chrome-remote-interface": stubEmpty, "googleapis": stubEmpty, "esbuild": stubEmpty,
      "pptxgenjs": join(HERE, "stubs", "pptxgenjs-global.ts"),
      "jszip": join(HERE, "stubs", "jszip-global.ts"),
    },
    define: { __EXTRACT_JS_LITERAL__: JSON.stringify(extractJs) },
    logLevel: "info",
  });
  const convertBundleJs = convResult.outputFiles![0].text;
  const convertBundlePath = join(HERE, "..", "addon-server", "public", "convert-bundle.js");
  writeFileSync(convertBundlePath, convertBundleJs);
  console.log(`convert-bundle → ${convertBundleJs.length.toLocaleString()} bytes → ${convertBundlePath}`);

  // 3. Vendor bundles (attach window.JSZip / window.PptxGenJS).
  //    UNLIKE the standalone page (build.ts), the add-on does NOT inline these:
  //    Apps Script's HtmlService sanitises/relays the sidebar HTML and corrupts
  //    a ~560 KB inlined minified blob (observed: "Uncaught SyntaxError: Invalid
  //    or unexpected token" → `PptxGenJS is not defined`). The sidebar is always
  //    online, so we load the vendors from a pinned CDN via <script src> (allowed
  //    in IFRAME sandbox mode) and inline only our own ~240 KB bundle.
  const JSZIP_CDN = "https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";
  const PPTX_CDN = "https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.1/dist/pptxgen.bundle.js";

  // 4. Sidebar HTML. Same dropzone UI as the standalone page, sized for the
  //    narrow Slides sidebar. google.script.run is injected by HtmlService.
  const sidebar = `<!DOCTYPE html>
<html>
<head>
<base target="_top">
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; }
  body { font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         margin: 0; padding: 12px; color: #111; }
  p.sub { color: #666; margin: 0 0 12px; font-size: 12px; }
  #dropzone { display: block; border: 2px dashed #bbb; border-radius: 10px; padding: 20px 12px;
              text-align: center; color: #555; cursor: pointer; transition: all .15s; }
  .btn { display: inline-block; padding: 7px 12px; font: inherit; border: 1px solid #ccc;
         background: white; border-radius: 6px; cursor: pointer; }
  .btn:hover { background: #f3f4f6; }
  #dropzone.hover { border-color: #3b82f6; background: #eff6ff; color: #1d4ed8; }
  #dropzone strong { color: #111; }
  #picker { display: none; }
  .row { display: flex; gap: 8px; margin: 12px 0; align-items: center; flex-wrap: wrap; }
  button { padding: 7px 12px; font: inherit; border: 1px solid #ccc; background: white;
           border-radius: 6px; cursor: pointer; }
  button:disabled { opacity: .4; cursor: not-allowed; }
  button.primary { background: #2563eb; color: white; border-color: #2563eb; }
  button.primary:disabled { background: #93c5fd; border-color: #93c5fd; }
  #file-list { margin: 0; padding: 0 0 0 20px; max-height: 110px; overflow: auto;
               font: 11px/1.5 ui-monospace, monospace; color: #444; }
  #file-list li { list-style: disc; }
  #progress-wrap { height: 6px; background: #eee; border-radius: 3px; overflow: hidden; margin: 6px 0; }
  #progress-bar { height: 100%; background: #2563eb; width: 0%; transition: width .15s; }
  #progress-label { font: 11px/1 ui-monospace, monospace; color: #666; min-height: 13px; }
  #log { font: 11px/1.45 ui-monospace, monospace; background: #0b1020; color: #cbd5e1;
         padding: 8px; border-radius: 6px; height: 160px; overflow: auto; margin-top: 8px; }
  #log .warn { color: #fbbf24; }
  #log .error { color: #f87171; }
  #paste-box { width: 100%; min-height: 44px; resize: vertical; margin: 8px 0 0;
               font: 11px/1.4 ui-monospace, monospace; color: #111;
               border: 1px solid #ccc; border-radius: 6px; padding: 6px 8px; }
  #paste-box:focus { outline: none; border-color: #2563eb; box-shadow: 0 0 0 2px #bfdbfe; }
  body.dragging { outline: 3px dashed #3b82f6; outline-offset: -6px; }
  body.dragging #dropzone { border-color: #3b82f6; background: #eff6ff; color: #1d4ed8; }
  #trouble { margin: 8px 0 0; font-size: 12px; color: #666; }
  #trouble summary { cursor: pointer; }
  #notice { margin: 8px 0 0; }
  #notice .box { padding: 8px 10px; border-radius: 6px; font-size: 12px; line-height: 1.4; }
  #notice .warn { background: #fef3c7; border: 1px solid #fcd34d; color: #92400e; }
  #notice .ok { background: #dcfce7; border: 1px solid #86efac; color: #166534; }
  #notice a { color: #1d4ed8; font-weight: 600; }
</style>
</head>
<body tabindex="0">
<p class="sub">Upload, drop, or paste slide HTML. It's converted locally and inserted right after the current slide.</p>

<!-- Native <label for> opens the OS file dialog on a real click — a
     programmatic input.click() is blocked inside the Apps Script sandbox. -->
<label id="dropzone" for="picker">
  <strong>Click to browse, or drop .html slides here</strong><br>
  <span id="file-count">0</span> file(s) queued.
</label>
<input type="file" id="picker" accept=".html,.htm" multiple>

<div class="row">
  <label class="btn" for="picker">📂 Browse slide files…</label>
  <button id="paste-btn">📋 Paste from clipboard</button>
</div>

<textarea id="paste-box" placeholder="…or click here and press ⌘V / Ctrl+V to paste slide HTML"></textarea>

<ul id="file-list"></ul>

<div class="row">
  <button id="insert-btn" class="primary" disabled>Insert after current slide</button>
  <button id="clear-btn">Clear</button>
</div>

<div id="notice"></div>
<details id="trouble">
  <summary>Insert failing? (permissions)</summary>
  <div class="row">
    <button id="reauth-btn">🔐 Re-authorize</button>
    <button id="testperm-btn">🔎 Test permissions</button>
  </div>
</details>

<div id="progress-wrap"><div id="progress-bar"></div></div>
<div id="progress-label"></div>
<div id="log"></div>

<script src="${JSZIP_CDN}"></script>
<script src="${PPTX_CDN}"></script>
<script>
${mainJs}
</script>
</body>
</html>`;

  // 5. Emit the project.
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "appsscript.json"), APPSSCRIPT_JSON);
  // Bake the deployed UI origin in from the environment so you don't hand-edit
  // Code.gs: `SERVER_ORIGIN=https://slides.yourdomain.com npx tsx browser/build-addon.ts`.
  const serverOrigin = process.env.SERVER_ORIGIN || "https://slides.example.com";
  if (serverOrigin === "https://slides.example.com") console.warn("  ⚠ SERVER_ORIGIN not set — Code.gs will point at the placeholder origin");
  writeFileSync(join(OUT, "Code.gs"), CODE_GS.split("https://slides.example.com").join(serverOrigin));
  writeFileSync(join(OUT, "Sidebar.html"), sidebar);

  const kb = (sidebar.length / 1024).toFixed(0);
  console.log(`\n✓ wrote Apps Script project to ${OUT}`);
  console.log(`    appsscript.json  (manifest)`);
  console.log(`    Code.gs          (${CODE_GS.length.toLocaleString()} bytes)`);
  console.log(`    Sidebar.html     (${kb} KB, bundle inlined)`);

  // Best-effort: copy Code.gs to the clipboard so it's one paste into Apps Script.
  // macOS pbcopy / Windows clip / Linux xclip|xsel — silently skipped if absent
  // (e.g. the Linux devcontainer has no clipboard).
  const codeGsPath = join(OUT, "Code.gs");
  const clip = process.platform === "darwin" ? "pbcopy"
    : process.platform === "win32" ? "clip"
    : "xclip -selection clipboard";
  try {
    execSync(`${clip} < ${JSON.stringify(codeGsPath)}`, { stdio: "ignore" });
    console.log(`    📋 Code.gs copied to clipboard — paste it straight into Apps Script`);
  } catch {
    console.log(`    (clipboard copy skipped — paste from ${codeGsPath})`);
  }
}

main().catch((e) => {
  console.error("build-addon failed:", e);
  process.exit(1);
});
